### ISSUE TITLE
Alerta housekeeping is causing massive amounts of email

### ISSUE THREAD

**Issue by rmyhren** [alerta/alerta#1086]
**Issue Summary**
When running alerta housekeeping, the spool fills up with a large number of emails 

**Environment**
- OS: Linux
- API version: 6.8.1
- Deployment: Self-hosted
- For self-hosted, WSGI environment: apache/mod_wsgi

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? SAML
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**
1. Run housekeeping

See email:

Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=86489>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Date: Thu,  6 Jun 2019 14:43:01 +0200 (CEST)
Status: ROTraceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/alerta", line 11, in <module>
    sys.exit(cli())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/alertaclient/cli.py", line 54, in cli
    config.get_remote_config()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/alertaclient/config.py", line 51, in get_remote_config
    remote_config = r.json()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by satterly** [comment]
cron generates an email when the command it has run exits with a non-zero exit code. You need to figure out what the error is and fix it.

**Comment by rmyhren** [comment]
My bad, wrong congig. Thanks for pointing me in the right debugging direction :)
