### ISSUE TITLE
Alerta 7.4.1 OIDC configuration check expects 'AZURE_TENANT' in config

### ISSUE THREAD

**Issue by brophyja** [alerta/alerta#1090]
We've been running Alerta 6.7.1 successfully with the 'AUTH_PROVIDER' set to 'keycloak'.

When testing Alerta 7.4.1 with a similar environment/configuration, the server exits with following exception:

```

[2019-10-02 21:06:03 +0000] [34] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/app-root/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/opt/app-root/src/wsgi.py", line 3, in <module>
    from alerta import app
  File "/opt/app-root/lib/python3.6/site-packages/alerta/__init__.py", line 29, in <module>
    app = create_app()
  File "/opt/app-root/lib/python3.6/site-packages/alerta/app.py", line 85, in create_app
    app.register_blueprint(auth_blueprint)
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1115, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/opt/app-root/lib/python3.6/site-packages/alerta/auth/__init__.py", line 10, in register
    oidc_config, _ = oidc.get_oidc_configuration(app)
  File "/opt/app-root/lib/python3.6/site-packages/alerta/auth/oidc.py", line 44, in get_oidc_configuration
    raise ApiError('Issuer Claim does not match Issuer URL used to retrieve OpenID configuration', 503)
```

In the Alerta 'oidc.py' library, there is a check that seems to assume the 'AUTH_PROVIDER' is azure and the 'AZURE_TENANT' is specified in the configuration:

```
43     if config['issuer'].format(tenantid=app.config['AZURE_TENANT']) != issuer_url:
44         raise ApiError('Issuer Claim does not match Issuer URL used to retrieve OpenID configuration', 503)
```

When lines 43-44 of 'oidc.py' are commented out, the Alerta 7.4.1 server starts and is able to handle Keycloak/Oauth authentication.

**Comment by satterly** [comment]
The error says 'Issuer Claim does not match Issuer URL used to retrieve OpenID configuration'. It has nothing to do with Azure.

Can you include your `alertad.conf` keycloak server settings so I can check that they are correct?

**Comment by brophyja** [comment]
I was confused by the below string format statement and jumped to an incorrect conclusion:

`config['issuer'].format(tenantid=app.config['AZURE_TENANT'])`

The Issuer Claim & URL string comparison did correctly determine that the two values were different.  The Issuer URL included the port (:443) of the SSO/Keycloak server while the Issuer Claim did not.  I modified the KEYCLOAK_URL parameter to remove the unnecessary port 443 designation in the URL, and the ApiError exception no longer occurs.

Thank you for your time.
