### ISSUE TITLE
Getting issue with alertad connecting to postgres

### ISSUE THREAD

**Issue by nkanne** [alerta/alerta#1092]
[root@alerta1 bin]# ./alertad run --port 8080
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/alerta/database/base.py", line 30, in load_backend
    return import_module('alerta.database.backends.%s' % backend)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/alerta/database/backends/postgres/__init__.py", line 1, in <module>
    from .base import *  # noqa
  File "/usr/local/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py", line 5, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./alertad", line 7, in <module>
    from alerta.commands import cli
  File "/usr/local/lib/python3.7/site-packages/alerta/__init__.py", line 29, in <module>
    app = create_app()
  File "/usr/local/lib/python3.7/site-packages/alerta/app.py", line 67, in create_app
    db.init_db(app)
  File "/usr/local/lib/python3.7/site-packages/alerta/database/base.py", line 44, in init_db
    cls = load_backend(backend)
  File "/usr/local/lib/python3.7/site-packages/alerta/database/base.py", line 32, in load_backend
    raise ImportError('Failed to load %s database backend' % backend)
ImportError: Failed to load postgres database backend

I in the versions file
__version__ = '7.4.1'

EC2 is running amazon linux 2

Postgres is on RDS in AWS

**Comment by nkanne** [comment]
sudo pip3 install psycopg2-binary
