### ISSUE TITLE
Gitlab OpenId authentication redirection fails

### ISSUE THREAD

**Issue by FloSew** [alerta/alerta#1114]
First, thank you for your application.

**Issue Summary**
After authorizing Alerta to use account on Gitlab, when redirecting, I get the following error on the interface:

> Sorry, there was a problem Please try again
> 
> Error: Expecting value: line 1 column 1 (char 0)

```
alerta.web    | 2019-12-03 14:48:59,305 DEBG 'nginx' stdout output:
alerta.web    | ip=\- [\03/Dec/2019:14:48:59 +0000] "\GET /?code=1983fe8554c76d44d7291a503d2d1d111ab70446a7026388f4c0cd0ee93ae4bd&state=sjykrn9ty48 HTTP/1.1" \200 \994 "\http://sop-containers-stag-dc1-3.test.fr:8080/login?redirect=%2Falerts" "\Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
alerta.web    | /web/ | /index.html | > GET /?code=1983fe8554c76d44d7291a503d2d1d111ab70446a7026388f4c0cd0ee93ae4bd&state=sjykrn9ty48 HTTP/1.1
alerta.web    |
alerta.web    | 2019-12-03 14:48:59,520 DEBG 'uwsgi' stdout output:
alerta.web    | 2019-12-03 14:48:59,519 urllib3.connectionpool[53]: [DEBUG] Starting new HTTPS connection (1): gitlab.priv.fr:443 request_id=1238a897-f548-4e0f-b05e-80ee55cded27 ip=172.17.45.254
alerta.web    |
alerta.web    | 2019-12-03 14:48:59,571 DEBG 'uwsgi' stdout output:
alerta.web    | 2019-12-03 14:48:59,570 urllib3.connectionpool[53]: [DEBUG] https://gitlab.priv.fr:443 "GET /.well-known/openid-configuration HTTP/1.1" 200 873 request_id=1238a897-f548-4e0f-b05e-80ee55cded27 ip=172.17.45.254
alerta.web    |
alerta.web    | 2019-12-03 14:48:59,578 DEBG 'uwsgi' stdout output:
alerta.web    | 2019-12-03 14:48:59,577 urllib3.connectionpool[53]: [DEBUG] Starting new HTTPS connection (1): gitlab.priv.fr:443 request_id=1238a897-f548-4e0f-b05e-80ee55cded27 ip=172.17.45.254
alerta.web    |
alerta.web    | 2019-12-03 14:48:59,640 DEBG 'uwsgi' stdout output:
alerta.web    | 2019-12-03 14:48:59,640 urllib3.connectionpool[53]: [DEBUG] https://gitlab.priv.fr:443 "POST /oauth/token HTTP/1.1" 500 2926 request_id=1238a897-f548-4e0f-b05e-80ee55cded27 ip=172.17.45.254
alerta.web    |
alerta.web    | 2019-12-03 14:48:59,647 DEBG 'uwsgi' stdout output:
alerta.web    | 2019-12-03 14:48:59,647 flask.app[53]: [ERROR] Expecting value: line 1 column 1 (char 0) request_id=1238a897-f548-4e0f-b05e-80ee55cded27 ip=172.17.45.254
alerta.web    | Traceback (most recent call last):
alerta.web    |   File "/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
alerta.web    |     rv = self.dispatch_request()
alerta.web    |   File "/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
alerta.web    |     return self.view_functions[rule.endpoint](**req.view_args)
alerta.web    |   File "/venv/lib/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
alerta.web    |     resp = make_response(f(*args, **kwargs))
alerta.web    |   File "/venv/lib/python3.6/site-packages/alerta/auth/oidc.py", line 79, in openid
alerta.web    |     token = r.json()
alerta.web    |   File "/venv/lib/python3.6/site-packages/requests/models.py", line 897, in json
alerta.web    |     return complexjson.loads(self.text, **kwargs)
alerta.web    |   File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
alerta.web    |     return _default_decoder.decode(s)
alerta.web    |   File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
alerta.web    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
alerta.web    |   File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
alerta.web    |     raise JSONDecodeError("Expecting value", s, err.value) from None
alerta.web    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
alerta.web    | 2019-12-03 14:48:59,652 DEBG 'uwsgi' stdout output:
alerta.web    |
alerta.web    |
alerta.web    | 2019-12-03 14:48:59,660 DEBG 'nginx' stdout output:
alerta.web    | ip=\- [\03/Dec/2019:14:48:59 +0000] "\POST /api/auth/gitlab HTTP/1.1" \500 \1358 "\http://sop-containers-stag-dc1-3.test.fr:8080/login?redirect=%2Falerts" "\Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
alerta.web    | /web | /api/auth/gitlab | > POST /api/auth/gitlab HTTP/1.1
alerta.web    |
alerta.web    | 2019-12-03 14:48:59,663 DEBG 'uwsgi' stdout output:
alerta.web    | [pid: 53|app: 0|req: 21/24] 172.17.45.254 () {50 vars in 1058 bytes} [Tue Dec  3 14:48:59 2019] POST /api/auth/gitlab => generated 1358 bytes in 143 msecs (HTTP/1.1 500) 3 headers in 144 bytes (1 switches on core 0)
alerta.web    |
```

**Environment**
- OS: [eg. Linux, Mac, Windows]
- Deployment: [Docker, self-hosted]
- Database: [Postgres]

- Docker compose file:
```
version: "3.7"

services:
  alerta.web:
    image: alerta/alerta-web:7.4.1
    container_name: alerta.web
    ports:
      - "8080:8080"
    depends_on:
      - alerta.db
    environment:
      - DEBUG=0
      - DATABASE_URL=postgres://postgres:postgres@alerta.db:5432/monitoring
      - AUTH_REQUIRED=True
      - SECRET_KEY=Xc64Z9FBP2EluTruXB*G^VTHM8!pP!C7
      - PLUGINS=remote_ip,reject,heartbeat,blackout,normalise,enhance
      - AUTH_PROVIDER=gitlab
      - GITLAB_URL=https://gitlab.priv.fr
      - OAUTH2_CLIENT_ID=5a47eb876f9b335621b72e6ffa331cee4177c67ea403967fa52ed7b497eb5771
      - OAUTH2_CLIENT_SECRET=08c7015575fa76f7ec3c7bac1d6f672c34fa926886d7cab77ffbd7cbd98c5b7c
    restart: always
  alerta.db:
    image: postgres:12
    container_name: alerta.db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
```

Please ask if more information is needed.

**Comment by FloSew** [comment]
Forgot to mention Gitlab version.

GitLab Community Edition 12.1.4

**Comment by FloSew** [comment]
Debugging with Flask, this is our Gitlab server that is returning an error 500.
