### ISSUE TITLE
Latest werkzeug broke Alerta

### ISSUE THREAD

**Issue by Samgarr** [alerta/alerta#1137]
**Issue Summary**
Latest (https://werkzeug.palletsprojects.com/en/master/changes/#version-1-0-0) release of Werkzeug includes breaking changes.

```
Feb 07 13:37:13 alerta1 alertad[12092]: Traceback (most recent call last):
Feb 07 13:37:13 alerta1 alertad[12092]:   File "wsgi.py", line 1, in <module>
Feb 07 13:37:13 alerta1 alertad[12092]:     from alerta import app
Feb 07 13:37:13 alerta1 alertad[12092]:   File "/usr/local/lib/python3.5/dist-packages/alerta/__init__.py", line 28, in <module>
Feb 07 13:37:13 alerta1 alertad[12092]:     from .app import create_app  # noqa isort:skip
Feb 07 13:37:13 alerta1 alertad[12092]:   File "/usr/local/lib/python3.5/dist-packages/alerta/app.py", line 8, in <module>
Feb 07 13:37:13 alerta1 alertad[12092]:     from werkzeug.contrib.fixers import ProxyFix
Feb 07 13:37:13 alerta1 alertad[12092]: ImportError: No module named 'werkzeug.contrib'
```

**Environment**
- OS: linux
- API version: latest
- Deployment: selfhosted
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: MongoDB

- Server config:
  Auth enabled? Yes
  Auth provider? No
  Customer views? No

**To Reproduce**

install Alerta with latest werkzeug dependecy

**Comment by satterly** [comment]
Fixed by #1095
