### ISSUE TITLE
Check LDAP auth works with Active Directory LDAPS

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#1208]
**Is your feature request related to a problem? Please describe.**

Does Alerta support SLDAP since Microsoft is deprecating normal LDAP? @cisco92

**Describe the solution you'd like**

Alerta LDAP auth should continue to work.

**Describe alternatives you've considered**

None.

**Additional context**

https://support.microsoft.com/en-us/help/4520412/2020-ldap-channel-binding-and-ldap-signing-requirements-for-windows
https://kb.sos-berlin.com/pages/viewpage.action?pageId=18778435

See also https://github.com/python-ldap/python-ldap/issues/309

**Comment by wagnst** [comment]
I think it is actually not working...

```
2020-04-29 14:46:42,974 DEBG 'uwsgi' stdout output:
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7f5ea44c2410> ldaps://ldap.xxx.de:636/ - SimpleLDAPObject.set_option
((17, 3), {})
=> result:
None

2020-04-29 14:46:42,975 DEBG 'uwsgi' stdout output:
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7f5ea44c2410> ldaps://ldap.xxx.de:636/ - SimpleLDAPObject.simple_bind
(('(&(objectClass=person)(uid=admin))', 'xxx', None, None), {})

2020-04-29 14:46:43,081 DEBG 'uwsgi' stdout output:
=> LDAPError - SERVER_DOWN: {'desc': "Can't contact LDAP server", 'info': '(unknown error code)'}

2020-04-29 14:46:43,086 DEBG 'uwsgi' stdout output:
2020-04-29 14:46:43,081 flask.app[25]: [ERROR] {'desc': "Can't contact LDAP server", 'info': '(unknown error code)'} request_id=4a743f2199d4b9ad0011d82ede01e8c1 ip=10.244.0.32
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/alerta/auth/basic_ldap.py", line 52, in login
    ldap_connection.simple_bind_s(userdn, password)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 445, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 439, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/venv/lib/python3.7/site-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'info': '(unknown error code)'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/venv/lib/python3.7/site-packages/alerta/auth/basic_ldap.py", line 56, in login
    raise ApiError(str(e), 500)
alerta.exceptions.ApiError: {'desc': "Can't contact LDAP server", 'info': '(unknown error code)'}
```
Latest version (docker) and `alertad.conf`:

```
AUTH_PROVIDER = 'ldap'
AUTH_REQUIRED = 'True'
LDAP_DOMAINS = {'xxx.com': '(&(objectClass=person)(uid=%s))'}
LDAP_DOMAINS_BASEDN = {'xxx.com': 'ou=xx,o=xx-dir'}
LDAP_DOMAINS_GROUP = {'xxx.com': '(&(objectClass=group)(cn=ebpg_xxx_co_ngmdw_*))'}
LDAP_URL = 'ldaps://ldap.xxx.de:636/'

```

**Comment by cisco92** [comment]
Hello.

I managed to get it working.
However I have a modified basic_ldap.py:

`
import sys
import ldap
from flask import current_app, jsonify, request
from flask_cors import cross_origin

from alerta.auth.utils import create_token, get_customers
from alerta.exceptions import ApiError
from alerta.models.permission import Permission
from alerta.models.user import User
from alerta.utils.audit import auth_audit_trail

from . import auth


@auth.route('/auth/login', methods=['OPTIONS', 'POST'])
@cross_origin(supports_credentials=True)
def login():
    # Retrieve required fields from client request
    try:
        login = request.json.get('username', None) or request.json['email']
        password = request.json['password']
    except KeyError:
        raise ApiError("must supply 'username' and 'password'", 401)


    username = login
    domain = current_app.config['DEFAULT_DOMAIN']
    email = ''
    email_verified = False

    # Validate LDAP domain
    if domain not in current_app.config['LDAP_DOMAINS']:
        raise ApiError('unauthorized domain', 403)

    userdn = current_app.config['LDAP_DOMAINS'][domain] % username

    # Attempt LDAP AUTH
    try:
        trace_level = 2
        ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_HARD)
        ldap.set_option(ldap.OPT_X_TLS_CACERTFILE, "/venv/lib/python3.6/site-packages/alerta/auth/cert.pem")
        ldap_connection = ldap.initialize(current_app.config['LDAP_URL'], trace_level=trace_level)
        ldap_connection.protocol_version = 3
        ldap_connection.set_option(ldap.OPT_REFERRALS, 0)
        # ldap_connection.set_option(ldap.OPT_X_TLS,ldap.OPT_X_TLS_DEMAND)
        ldap_connection.bind_s(userdn, password)
    except ldap.INVALID_CREDENTIALS:
        raise ApiError('invalid username or password', 401)
    except Exception as e:
        raise ApiError(str(e), 500)


    emaildn = current_app.config['LDAP_DOMAINS_SEARCH_DN'][domain]
    emailfilter = current_app.config['LDAP_DOMAINS_SEARCH_FILTER'][domain] % username

    # Create user if not yet there
    user = User.find_by_username(username=login)
    if not user:
        try:
            emailattr = ['mail']
            ldap_result = ldap_connection.search_s(emaildn, ldap.SCOPE_SUBTREE, emailfilter, emailattr)
            email = ldap_result[0][1]['mail'][0].decode(sys.stdout.encoding)
            email_verified = True
        except Exception as e:
            raise ApiError(str(e), 500)

        user = User(name=username, login=login, password='', email=email,
                    roles=[], text='LDAP user', email_verified=email_verified)
        try:
            user = user.create()
        except Exception as e:
            ApiError(str(e), 500)

    # Assign customers & update last login time
    groups = list()
    try:
        groups_filters = current_app.config.get('LDAP_DOMAINS_GROUP', {})
        base_dns = current_app.config.get('LDAP_DOMAINS_BASEDN', {})
        if domain in groups_filters and domain in base_dns:
            resultID = ldap_connection.search(
                base_dns[domain],
                ldap.SCOPE_SUBTREE,
                groups_filters[domain].format(username=username, email=email, userdn=userdn),
                ['cn']
            )
            resultTypes, results = ldap_connection.result(resultID)
            for _dn, attributes in results:
                groups.append(attributes['cn'][0].decode('utf-8'))
    except ldap.LDAPError as e:
        raise ApiError(str(e), 500)

    # Check user is active
    if user.status != 'active':
        raise ApiError('User {} not active'.format(login), 403)
    user.update_last_login()

    scopes = Permission.lookup(login=login, roles=user.roles + groups)
    customers = get_customers(login=login, groups=[user.domain] + groups)

    auth_audit_trail.send(current_app._get_current_object(), event='basic-ldap-login', message='user login via LDAP',
                          user=login, customers=customers, scopes=scopes, resource_id=user.id, type='user',
                          request=request)

    # Generate token
    token = create_token(user_id=user.id, name=user.name, login=user.email, provider='ldap', customers=customers,
                         scopes=scopes, roles=user.roles, email=user.email, email_verified=user.email_verified)
    return jsonify(token=token.tokenize)
`

However for this I suppose this is the only thing that is intressting:
`
ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_HARD)
ldap.set_option(ldap.OPT_X_TLS_CACERTFILE, "/venv/lib/python3.6/site-packages/alerta/auth/cert.pem")
ldap_connection = ldap.initialize(current_app.config['LDAP_URL'], trace_level=trace_level)
`
and in alertad.conf 
`LDAP_URL = 'ldaps://rldap.3internal.local:636'`

**Comment by wagnst** [comment]
@cisco92 how about a proper pull request?

**Comment by cisco92** [comment]
@wagnst sure, I will make a pull request with changes to alertad.conf where you can set if it's ldap or ldaps, and the appropriate changes to basic_ldap.py. Will see if I can make it today.

**Comment by cisco92** [comment]
@wagnst @satterly https://github.com/alerta/alerta/pull/1219

**Comment by olivluca** [comment]
Are you sure that's needed? Maybe it works here because the dc is samba4, but I just had to set LDAP_ALLOW_SELF_SIGNED_CERT=True
(which in fact turns off certificate validation)

**Comment by cisco92** [comment]
@olivluca depends on the LDAP server, alot of configurations does not allow that. I tried alot of options without ca cert. Are you really using ldaps with ldaps port ?

**Comment by olivluca** [comment]
Yes, I'am. Granted, for every other service I specify the ca file, and usually I prefer starttls instead of ldaps, but alerta worked with LDAP_ALLOW_SELF_SIGNED_CERT=True. Without it gave me the error "Strong(er) authentication required".
My server is samba 4 though, not ms, but it should behave similarly.

**Comment by KlavsKlavsen** [comment]
I adjusted the PR to enable above - and with that It should work, so I can remove option for allowing self-signed certs.
Granting admin role based on LDAP group membership I have yet to get working, but hope I'll find a way to make it work as-is.

**Comment by satterly** [comment]
I'm pretty sure there's work still to be done here. Does anyone know what is still outstanding?

**Comment by CasperGN** [comment]
@satterly, I've tested using the standard config of https://github.com/osixia/docker-openldap, referenced the code as-is and the docs at https://www.python-ldap.org/en/python-ldap-3.3.0/reference/ldap.html#tls-options 

And it seems the `.set_option`'s are set on the ldap module rather than the connection object. 
I cannot see references to the `.start_tls_s()` either.

I've tested with the following:

```python
import ldap

ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_HARD)
ldap.set_option(ldap.OPT_X_TLS_NEWCTX, 0)

conn = ldap.initialize('ldap://localhost')
conn.simple_bind_s('admin', 'admin')
```

Which yields the following on sniffing:
![ksnip_20201107-144141](https://user-images.githubusercontent.com/5549643/98442861-b5972000-2107-11eb-9cab-c146706d06da.png)

When using:

```python
import ldap

conn = ldap.initialize('ldaps://localhost')
conn.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_HARD)
conn.set_option(ldap.OPT_X_TLS_NEWCTX, 0)
conn.start_tls_s()
conn.simple_bind_s('admin', 'admin')
```

I get the expected result when sniffing:
![ksnip_20201107-144922](https://user-images.githubusercontent.com/5549643/98442954-8a610080-2108-11eb-9688-7f2492cebc72.png)


I'd recon the following changes:
* Set the `.set_option()` on the connection object rather than the module (although setting on the module _may_ work)
* Ensure that `.start_tls_s()` is called on the connection object prior to the `.simple_bind_s()`

Also as a side note, I'd look into 
https://github.com/alerta/alerta/blob/master/alerta/auth/basic_ldap.py#L46

As I don't think it yields as expected. The docs state:
```
Used internally by slapd server.
```

As another reference the demo [here ](https://github.com/python-ldap/python-ldap/blob/master/Demo/initialize.py) may be valuable.

Cheers,
Casper

**Comment by satterly** [comment]
@CasperGN Thanks for that. Very useful. 👍

**Comment by satterly** [comment]
Closing due to inactivity. LDAPS with Active Directory should work -- if issues remain, please reopen with details.
