### ISSUE TITLE
Unable to access alerta API due to error in config

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [alerta/alerta#1211]
**Issue Summary**

**Environment**
- OS: N/A
- API version: Using image `alerta/alerta-web:7.5.1`
- Deployment: Kubernetes v.1.15 on GKE
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]

- Database: Postgres

- Server config:
  Auth enabled? No
  Auth provider? N/A
  Customer views? N/A
  (or provide the `/config` endpoint output)

- web UI version: Using image `alerta/alerta-web:7.5.1`
- CLI version: Using image `alerta/alerta-web:7.5.1`

**To Reproduce**
1. Deploying alerta using the helm chart
2. Trying to access the exposed url

Getting the error below

<img width="442" alt="Screenshot 2020-05-03 at 4 10 28 PM" src="https://user-images.githubusercontent.com/50835081/80915209-84552600-8d59-11ea-84fd-8a6f61e0ae5b.png">

logs:

```
alerta-758bc87dcf-m8rd6 alerta Error: Failed to get config from http://localhost:8080/api/config. Reason: 500 Server Error: Internal Server Error for url: http://localhost:8080/api/config
```

From within the pod

```
alerta@alerta-758bc87dcf-m8rd6:/web$ cat config.json
{"endpoint": "/api"}
alerta@alerta-758bc87dcf-m8rd6:/web$ curl http://localhost:8080/api/config
Internal Server Erroralerta@alerta-758bc87dcf-m8rd6:/web$ curl http://localhost:8080/api/config
```

**Comment by pantelis-karamolegkos** [comment]
Accessing the web endpoint seems ok

```
▶ curl -kI https://my.alerta.url
HTTP/2 200
server: istio-envoy
date: Sun, 03 May 2020 13:53:50 GMT
content-type: text/html
content-length: 3034
last-modified: Tue, 03 Mar 2020 20:26:47 GMT
etag: "5e5ebd87-bda"
accept-ranges: bytes
x-envoy-upstream-service-time: 2
```

**Comment by satterly** [comment]
What's the actual API error that is being returned? ie. the response body for the 500 error.

**Comment by pantelis-karamolegkos** [comment]
```
▶ curl -k https://my.alerta.url
Internal Server Error%
```

No further details...

**Comment by satterly** [comment]
Find the error in the server logs then. Any error anywhere that pointed to something specific. Otherwise I can't help you.

**Comment by pantelis-karamolegkos** [comment]
The only error appearing in server logs is this


```
alerta-5d7db46658-jpdkm alerta Error: Failed to get config from http://localhost:8080/api/config. Reason: 500 Server Error: Internal Server Error for url: http://localhost:8080/api/config
```

**Comment by pantelis-karamolegkos** [comment]
Also discovered this one


```
alerta-5d7db46658-jpdkm alerta --- no python application found, check your startup logs for errors ---
```

**Comment by pantelis-karamolegkos** [comment]
Do I need another image for the python app? I was under the impression the `alerta-web` image included both web and the server....

**Comment by pantelis-karamolegkos** [comment]
I have also enabled `DEBUG` (I think) in my configmap


```
▶ k get configmap alerta -o yaml
apiVersion: v1
data:
  alertad.conf: |2

    DEBUG = True
```

**Comment by satterly** [comment]
The "alerta-web" image on DockerHub contains everything you need. Find the request causing the error in the docker container logs. Until then I can't help.

**Comment by pantelis-karamolegkos** [comment]
Discovered this


```
alerta-5d7db46658-jpdkm alerta Traceback (most recent call last):
alerta-5d7db46658-jpdkm alerta server closed the connection unexpectedly
alerta-5d7db46658-jpdkm alerta  This probably means the server terminated abno
rmally
alerta-5d7db46658-jpdkm alerta  before or while processing the request.
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,360 DEBG 'uwsgi' stdout out
put:
alerta-5d7db46658-jpdkm alerta Traceback (most recent call last):
alerta-5d7db46658-jpdkm alerta   File "./wsgi.py", line 1, in <module>
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,360 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta     from alerta import app
alerta-5d7db46658-jpdkm alerta   File "/venv/lib/python3.7/site-packages/alerta/__init__.py", line 29, in <module>
alerta-5d7db46658-jpdkm alerta     app = create_app()
alerta-5d7db46658-jpdkm alerta   File "/venv/lib/python3.7/site-packages/alerta/app.py", line 67, in create_app
alerta-5d7db46658-jpdkm alerta     db.init_db(app)
alerta-5d7db46658-jpdkm alerta   File "/venv/lib/python3.7/site-packages/alerta/database/base.py", line 47, in init_db
alerta-5d7db46658-jpdkm alerta     self.create_engine(app, uri=app.config['DATABASE_URL'], dbname=app.config['DATABASE_NAME'])
alerta-5d7db46658-jpdkm alerta   File "/venv/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py", line 64, in create_engine
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,361 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta     conn = self.connect()
alerta-5d7db46658-jpdkm alerta   File "/venv/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py", line 104, in connect
alerta-5d7db46658-jpdkm alerta     raise RuntimeError('Database connect error. Failed to connect after {} retries.'.format(MAX_RETRIES))
alerta-5d7db46658-jpdkm alerta RuntimeError: Database connect error. Failed to connect after 5 retries.
alerta-5d7db46658-jpdkm alerta unable to load app 0 (mountpoint='') (callable not found or import error)
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,361 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta mounting wsgi:app on /api
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,365 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta Traceback (most recent call last):
alerta-5d7db46658-jpdkm alerta   File "/usr/local/lib/python3.7/logging/config.py", line 388, in resolve
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,365 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta     found = getattr(found, frag)
alerta-5d7db46658-jpdkm alerta AttributeError: module 'alerta' has no attribute 'utils'
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta During handling of the above exception, another exception occurred:
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta Traceback (most recent call last):
alerta-5d7db46658-jpdkm alerta   File "/usr/local/lib/python3.7/logging/config.py", line 543, in configure
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,365 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta     formatters[name])
alerta-5d7db46658-jpdkm alerta   File "/usr/local/lib/python3.7/logging/config.py", line 654, in configure_formatter
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,366 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta     result = self.configure_custom(config)
alerta-5d7db46658-jpdkm alerta   File "/usr/local/lib/python3.7/logging/config.py", line 469, in configure_custom
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,366 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta     c = self.resolve(c)
alerta-5d7db46658-jpdkm alerta   File "/usr/local/lib/python3.7/logging/config.py", line 391, in resolve
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,366 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta     found = getattr(found, frag)
alerta-5d7db46658-jpdkm alerta AttributeError: module 'alerta' has no attribute 'utils'
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta The above exception was the direct cause of the following exception:
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,366 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta Traceback (most recent call last):
alerta-5d7db46658-jpdkm alerta   File "./wsgi.py", line 1, in <module>
alerta-5d7db46658-jpdkm alerta     from alerta import app
alerta-5d7db46658-jpdkm alerta   File "/venv/lib/python3.7/site-packages/alerta/__init__.py", line 29, in <module>
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,366 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta     app = create_app()
alerta-5d7db46658-jpdkm alerta   File "/venv/lib/python3.7/site-packages/alerta/app.py", line 53, in create_app
alerta-5d7db46658-jpdkm alerta     logger.setup_logging(app)
alerta-5d7db46658-jpdkm alerta   File "/venv/lib/python3.7/site-packages/alerta/utils/logging.py", line 97, in setup_logging
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,367 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta     'handlers': app.config['LOG_HANDLERS']
alerta-5d7db46658-jpdkm alerta   File "/usr/local/lib/python3.7/logging/config.py", line 800, in dictConfig
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,367 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta     dictConfigClass(config).configure()
alerta-5d7db46658-jpdkm alerta   File "/usr/local/lib/python3.7/logging/config.py", line 546, in configure
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,367 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta     'formatter %r' % name) from e
alerta-5d7db46658-jpdkm alerta ValueError: Unable to configure formatter 'default'
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,367 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta unable to load app 0 (mountpoint='/api') (callable not found or import error)
alerta-5d7db46658-jpdkm alerta *** no app loaded. going in full dynamic mode ***
alerta-5d7db46658-jpdkm alerta *** uWSGI is running in multiple interpreter mode ***
alerta-5d7db46658-jpdkm alerta spawned uWSGI master process (pid: 11)
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,369 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta spawned uWSGI worker 1 (pid: 20, cores: 1)
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,369 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta spawned uWSGI worker 2 (pid: 21, cores: 1)
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,370 DEBG 'uwsgi' stdout output:
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,367 DEBG 'uwsgi' stdout out
put:
alerta-5d7db46658-jpdkm alerta     'formatter %r' % name) from e
alerta-5d7db46658-jpdkm alerta ValueError: Unable to configure formatter 'defa
ult'
alerta-5d7db46658-jpdkm alerta
alerta-5d7db46658-jpdkm alerta 2020-05-03 13:31:43,367 DEBG 'uwsgi' stdout out
put:
alerta-5d7db46658-jpdkm alerta unable to load app 0 (mountpoint='/api') (calla
ble not found or import error)
alerta-5d7db46658-jpdkm alerta *** no app loaded. going in full dynamic mode *
**
```

I am also constantly seeing this in `postgres` logs


```
alerta-postgresql-0 alerta-postgresql 2020-05-03 14:21:35.228 GMT [6274] LOG:  invalid length of startup packet
```

**Comment by pantelis-karamolegkos** [comment]
The DB url is the default one

```
    DATABASE_URL = "postgresql://alerta:changeme@alerta-postgresql:5432/monitoring"
```

However when trying to connect to it directly from alerta pod, it fails


```
alerta@alerta-758bc87dcf-4r9bz:/$ psql postgresql://alerta:changeme@alerta-postgresql:5432/monitoring
psql: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Comment by satterly** [comment]
You didn't provide your server config in the issue template. Can you provide it now?

**Comment by pantelis-karamolegkos** [comment]
You mean those 2 files?

```
alerta@alerta-758bc87dcf-4r9bz:/$ cat app/alerta.conf
[DEFAULT]
endpoint = http://localhost:8080/api

alerta@alerta-758bc87dcf-4r9bz:/$ cat app/alertad.conf

DEBUG = True
DATABASE_URL = "postgresql://alerta:changeme@alerta-postgresql:5432/monitoring"
```

**Comment by satterly** [comment]
The Alerta error is due to not being able to contact the database...
```
   conn = self.connect()
alerta-5d7db46658-jpdkm alerta   File "/venv/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py", line 104, in connect
alerta-5d7db46658-jpdkm alerta     raise RuntimeError('Database connect error. Failed to connect after {} retries.'.format(MAX_RETRIES))
alerta-5d7db46658-jpdkm alerta RuntimeError: Database connect error. Failed to connect after 5 retries.
```
Fix that and Alerta should work. That's as much I as I know as I didn't write this helm chart and don't currently use Kubernetes to run Alerta.

**Comment by pantelis-karamolegkos** [comment]
OK thanks, closing this.
