### ISSUE TITLE
Exception on Alert.serialize

### ISSUE THREAD

**Issue by escoand** [alerta/alerta#1279]
**Issue Summary**
An exception is thrown when using `Alert.serialize` while housekeeping. The alert is not known yet, but the exception should be handled anyway.

**Environment**
- OS: Linux
- API version: 8.0.1
- Deployment: Docker
- Database: MongoDB
- Server config:
  Auth enabled? Yes
  Auth provider? OpenID
  Customer views? Ye
- web UI version: 8.0.0
- CLI version: 7.5.7

**To Reproduce**
Not sure, still investigating how this could happen.

**Expected behavior**
Catch the exception and log or skip accordingly.

**Screenshots**

**Additional context**
The ordering gets maybe cluttered by logstash and kibana.
```
AttributeError: 'NoneType' object has no attribute 'update_time'
  File "/venv/lib/python3.7/site-packages/alerta/models/alert.py", line 149, in serialize
    updated = plugin.take_action(alert, action, text, timeout=timeout, config=wanted_config)
  File "/venv/lib/python3.7/site-packages/alerta/utils/api.py", line 97, in process_action
Traceback (most recent call last):
    alert, _, text, timeout = process_action(alert, action='timeout', text='', timeout=current_app.config['ALERT_TIMEOUT'])
    'history': [h.serialize for h in sorted(self.history, key=lambda x: x.update_time)]
alerta.exceptions.ApiError: Error while running action plugin 'myplugin': 'NoneType' object has no attribute 'update_time'
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/alerta/models/alert.py", line 149, in <lambda>
  File "/venv/lib/python3.7/site-packages/alerta/utils/api.py", line 104, in process_action
ERROR Error while running action plugin 'myplugin': 'NoneType' object has no attribute 'update_time'
  File "/venv/lib/python3.7/site-packages/alerta/management/views.py", line 172, in housekeeping
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
    data = alert.serialize
  File "/venv/lib/python3.7/site-packages/myplugin.py", line 215, in take_action
During handling of the above exception, another exception occurred:
    raise ApiError("Error while running action plugin '{}': {}".format(plugin.name, str(e)))
    'history': [h.serialize for h in sorted(self.history, key=lambda x: x.update_time)]
  File "/venv/lib/python3.7/site-packages/alerta/management/views.py", line 181, in housekeeping
    rv = self.dispatch_request()
    return f(*args, **kwargs)
  File "/venv/lib/python3.7/site-packages/alerta/auth/decorators.py", line 53, in wrapped
  File "/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
alerta.exceptions.ApiError: Error while running action plugin 'myplugin': 'NoneType' object has no attribute 'update_time'
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    raise ApiError(str(e), 500)
    resp = make_response(f(*args, **kwargs))
    return self.view_functions[rule.endpoint](**req.view_args)
```

**Comment by escoand** [comment]
Found the alert:
```json
body: {
  "alerts": [
    {
      "attributes": {
        "script": "check-log",
        "wiki link": "<a href=\"...\" target=\"wiki\">Wiki</a>"
      },
      "correlate": [],
      "createTime": "2020-07-18T23:35:11.174Z",
      "customer": "...",
      "duplicateCount": 0,
      "environment": "...",
      "event": "...",
      "group": "Misc",
      "history": [
        {
          "event": "...",
          "href": "/alert/a0201a66-c2f3-4c6a-ab3d-c72455d3ba5a",
          "id": "a0201a66-c2f3-4c6a-ab3d-c72455d3ba5a",
          "severity": "major",
          "status": "open",
          "text": "",
          "type": "new",
          "updateTime": "2020-07-18T23:35:11.174Z",
          "user": "alerta",
          "value": "1 major lines"
        },
        {
          "event": "...",
          "href": "/alert/a0201a66-c2f3-4c6a-ab3d-c72455d3ba5a",
          "id": "a0201a66-c2f3-4c6a-ab3d-c72455d3ba5a",
          "severity": "major",
          "status": "shelved",
          "text": "",
          "type": "shelve",
          "updateTime": "2020-07-20T00:07:15.178Z",
          "user": "...",
          "value": "1 major lines"
        }
      ],
      "href": "/alert/a0201a66-c2f3-4c6a-ab3d-c72455d3ba5a",
      "id": "a0201a66-c2f3-4c6a-ab3d-c72455d3ba5a",
      "lastReceiveId": "a0201a66-c2f3-4c6a-ab3d-c72455d3ba5a",
      "lastReceiveTime": "2020-07-18T23:35:11.179Z",
      "origin": "...",
      "previousSeverity": "unknown",
      "rawData": "\u001b[31m132 errors found.\u001b[0m",
      "receiveTime": "2020-07-18T23:35:11.179Z",
      "repeat": false,
      "resource": "...",
      "service": [
        "Sysmon"
      ],
      "severity": "major",
      "status": "shelved",
      "tags": [],
      "text": "",
      "timeout": 7200,
      "trendIndication": "moreSevere",
      "type": "exceptionAlert",
      "updateTime": "2020-07-20T00:07:15.178Z",
      "value": "1 major lines"
    }
  ],
  "autoRefresh": true,
  "lastTime": "2020-07-18T23:35:11.179Z",
  "more": false,
  "page": 1,
  "pageSize": 50,
  "pages": 1,
  "severityCounts": {
    "major": 1
  },
  "status": "ok",
  "statusCounts": {
    "shelved": 1
  },
  "total": 1
}
```

**Comment by escoand** [comment]
Ok, it's maybe not this concrete alert. I've closed it and now the next one is throwing the exception. Is there maybe some side effect with the logging in my `take_action` method?

```python
    def take_action(self, alert, action, text, **kwargs):
        LOG.debug("take_action %s for %s called: %s", action, alert, text)
        data = alert.serialize
```

**Comment by satterly** [comment]
I modified the `test_plugins.py` test to add your lines and it worked without error so I don't know what's wrong ...

```
class CustActionPlugin1(PluginBase):

    def pre_receive(self, alert, **kwargs):
        return alert

    def post_receive(self, alert, **kwargs):
        return

    def status_change(self, alert, status, text, **kwargs):
        return alert, status, text

    def take_action(self, alert, action, text, **kwargs):

        LOG.debug("take_action %s for %s called: %s", action, alert, text)
        data = alert.serialize
        print(data)

        if action == 'createTicket':
            alert.status = 'ack'
            text = text + ' (ticket #12345)'

        if action == 'updateTicket':
            # do not change status
            alert.attributes['up'] = 'down'
            text = text + ' (ticket #12345)'

        if action == 'resolveTicket':
            alert.status = 'closed'
            alert.tags.append('true')
            text = text + ' (ticket #12345)'

        alert.tags.append('aSingleTag')  # one tag only
        alert.tags.extend(['aDouble:Tag', 'a:Triple:Tag'])  # multiple tags as a list

        return alert, action, text
```

```
$ TOXENV="postgres -- tests/test_plugins.py::PluginsTestCase::test_add_and_remove_tags" make test

====================================================================== test session starts ======================================================================
platform darwin -- Python 3.9.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: .tox/postgres/.pytest_cache
rootdir: /Users/nsatterl/Projects/alerta
plugins: requests-mock-1.8.0
collected 1 item                                                                                                                                                

tests/test_plugins.py {'id': '28556dce-483e-42b8-83d9-d36b9a3a67fd', 'href': 'http://localhost/alert/28556dce-483e-42b8-83d9-d36b9a3a67fd', 'resource': 'C8E0B451', 'event': 'node_down', 'environment': 'Production', 'severity': 'critical', 'correlate': ['node_down', 'node_marginal', 'node_up'], 'status': 'open', 'service': ['Network'], 'group': 'Misc', 'value': None, 'text': '', 'tags': ['Production', 'Development'], 'attributes': {'aaa': 'pre1', 'old': 'pre1'}, 'origin': 'pytest/nicholass-mbp.lan', 'type': 'exceptionAlert', 'createTime': datetime.datetime(2020, 11, 3, 21, 48, 40, 629000), 'timeout': 86400, 'rawData': None, 'customer': None, 'duplicateCount': 0, 'repeat': False, 'previousSeverity': 'indeterminate', 'trendIndication': 'moreSevere', 'receiveTime': datetime.datetime(2020, 11, 3, 21, 48, 40, 635000), 'lastReceiveId': '28556dce-483e-42b8-83d9-d36b9a3a67fd', 'lastReceiveTime': datetime.datetime(2020, 11, 3, 21, 48, 40, 635000), 'updateTime': datetime.datetime(2020, 11, 3, 21, 48, 40, 635000), 'history': [{'id': '28556dce-483e-42b8-83d9-d36b9a3a67fd', 'href': 'http://localhost/alert/28556dce-483e-42b8-83d9-d36b9a3a67fd', 'event': 'node_down', 'severity': 'critical', 'status': 'open', 'value': None, 'text': '', 'type': 'new', 'updateTime': datetime.datetime(2020, 11, 3, 21, 48, 40, 629000), 'user': None, 'timeout': 86400}]}
.

======================================================================= 1 passed in 0.70s =======================================================================
postgres run-test-post: commands[0] | -dropdb alerta
____________________________________________________________________________ summary ____________________________________________________________________________
  postgres: commands succeeded
  congratulations :)

```

So unless you can reliably reproduce this error in a test (ideally) I'm going to have to close this. Thanks.
