### ISSUE TITLE
custom webhook always returns http500

### ISSUE THREAD

**Issue by ArjunDandagi** [alerta/alerta#1291]
Hoping for some guidance with a custom webhook i'm trying to implement to use with splunk (just trying out post method from local as of now , i haven't thought about exact payload yet).

Version info
alertad 8.3.0

Install info
centos 7.5
MongoDB
self hosted
running in foreground
No auth

webhookcode: 

```
from alerta.models.alert import Alert
from alerta.webhooks import WebhookBase
import json

class SplunkWebhook(WebhookBase):

    def incoming(self, query_string, payload):
        return Alert(
            resource="UKGR",
            event="splunk_alert",
            environment="Production",
            severity="ERROR",
            service="splunk",
            group="Application",
            value="sample",
            text="something is missing",
            tags=list(),
            origin="splunk",
            raw_data=json.dumps(payload)
        )

```
setup.py
```
from setuptools import setup, find_packages

version = '5.0.1'

setup(
    name="alerta-splunk",
    version=version,
    description='Alerta webhook for splunk',
    url='https://github.com/alerta/alerta-contrib',
    license='MIT',
    author='Nick Satterly',
    author_email='nick.satterly@gmail.com',
    packages=find_packages(),
    py_modules=['alerta_splunk'],
    install_requires=[
    ],
    include_package_data=True,
    zip_safe=True,
    entry_points={
        'alerta.webhooks': [
            'splunk = alerta_splunk:SplunkWebhook'
        ]
    }
)

```
REQUEST:
```
curl -v -H "Content-Type: application/json" -X POST localhost:5000/webhooks/splunk -d '{"ji":"ko"}'
* About to connect() to localhost port 5000 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> POST /webhooks/splunk HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:5000
> Accept: */*
> Content-Type: application/json
> Content-Length: 11
>
* upload completely sent off: 11 out of 11 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 500 INTERNAL SERVER ERROR
< Content-Type: application/json
< Content-Length: 252
< Access-Control-Allow-Origin: *
< X-Request-ID: 159c201b-91ed-42f9-99e3-523fdd6f9b44
< Server: Werkzeug/1.0.1 Python/3.8.0
< Date: Thu, 20 Aug 2020 06:23:23 GMT
<
{"code":500,"errors":null,"message":"Error while running pre-receive plugin 'alerta.plugins.blackout': $nin needs an array, full error: {'ok': 0.0, 'errmsg': '$nin needs an array', 'code': 2, 'codeName': 'BadValue'}","requestId":null,"status":"error"}
* Closing connection 0
```

LOGS IN SERVER:

```
2020-08-20 06:23:23,244 alerta.app[22802]: [ERROR] Error while running pre-receive plugin 'alerta.plugins.blackout': $nin needs an array, full error: {'ok': 0.0, 'errmsg': '$nin needs an array', 'code': 2, 'codeName': 'BadValue'} request_id=159c201b-91ed-42f9-99e3-523fdd6f9b44 ip=127.0.0.1
Traceback (most recent call last):
  File "/home/app/.local/lib/python3.8/site-packages/alerta/utils/api.py", line 40, in process_alert
    alert = plugin.pre_receive(alert, config=wanted_config)
  File "/home/app/.local/lib/python3.8/site-packages/alerta/plugins/blackout.py", line 27, in pre_receive
    if alert.is_blackout():
  File "/home/app/.local/lib/python3.8/site-packages/alerta/models/alert.py", line 412, in is_blackout
    return db.is_blackout_period(self)
  File "/home/app/.local/lib/python3.8/site-packages/alerta/database/backends/mongodb/base.py", line 1176, in is_blackout_period
    if self.get_db().blackouts.find_one(query):
  File "/home/app/.local/lib/python3.8/site-packages/pymongo/collection.py", line 1319, in find_one
    for result in cursor.limit(-1):
  File "/home/app/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1207, in next
    if len(self.__data) or self._refresh():
  File "/home/app/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1124, in _refresh
    self.__send_message(q)
  File "/home/app/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 999, in __send_message
    response = client._run_operation_with_response(
  File "/home/app/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1368, in _run_operation_with_response
    return self._retryable_read(
  File "/home/app/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1471, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "/home/app/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1360, in _cmd
    return server.run_operation_with_response(
  File "/home/app/.local/lib/python3.8/site-packages/pymongo/server.py", line 136, in run_operation_with_response
    _check_command_response(
  File "/home/app/.local/lib/python3.8/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response,
pymongo.errors.OperationFailure: $nin needs an array, full error: {'ok': 0.0, 'errmsg': '$nin needs an array', 'code': 2, 'codeName': 'BadValue'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/.local/lib/python3.8/site-packages/alerta/webhooks/custom.py", line 52, in custom
    alert = process_alert(alert)
  File "/home/app/.local/lib/python3.8/site-packages/alerta/utils/api.py", line 47, in process_alert
    raise RuntimeError("Error while running pre-receive plugin '{}': {}".format(plugin.name, str(e)))
RuntimeError: Error while running pre-receive plugin 'alerta.plugins.blackout': $nin needs an array, full error: {'ok': 0.0, 'errmsg': '$nin needs an array', 'code': 2, 'codeName': 'BadValue'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/app/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/app/.local/lib/python3.8/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/app/.local/lib/python3.8/site-packages/alerta/auth/decorators.py", line 127, in wrapped
    return f(*args, **kwargs)
  File "/home/app/.local/lib/python3.8/site-packages/alerta/webhooks/custom.py", line 66, in custom
    raise ApiError(str(e), 500)
alerta.exceptions.ApiError: Error while running pre-receive plugin 'alerta.plugins.blackout': $nin needs an array, full error: {'ok': 0.0, 'errmsg': '$nin needs an array', 'code': 2, 'codeName': 'BadValue'}
```

Any help would be greatly appreciated.

**Comment by sherrygopal** [comment]
reading the manual of writing plugin it seems your webhook should have function such as

```
class ExamplePlugin(PluginBase):

    def __init__(self, name=None):

        # plugin-specific init goes here
        # if not required, leave "__init__()" out completely

        super(ExamplePlugin, self).__init__(name)

    def pre_receive(self, alert):

        # reject or modify an alert before it hits the database

        return alert

    def post_receive(self, alert):

        # after alert saved in database, forward alert to external systems

        return

    def status_change(self, alert, status, text):

        # triggered by external status changes, used by integrations

        return
```

Try using pre_receive instead of incoming.

**Comment by ArjunDandagi** [comment]
No ..I figured out what was the mistake . .. there are certain plugins that run and reject the Alert if they don't match certain criteria. Thanks.
