### ISSUE TITLE
Alerta webhook suddenly fails to parse received alerts from AlertManager

### ISSUE THREAD

**Issue by KlavsKlavsen** [alerta/alerta#1327]
**Issue Summary**
After I added an extra label called 'environment' into my prometheus alerts (previously they only had 'severity' label) - Alerta suddenly fails when receiving alerts from alertmanager:
```
DETAIL:  Input has too few columns.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
   File "/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
     rv = self.dispatch_request()
   File "/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
     resp = make_response(f(*args, **kwargs))
   File "/venv/lib/python3.7/site-packages/alerta/auth/decorators.py", line 127, in wrapped
     return f(*args, **kwargs)
   File "/venv/lib/python3.7/site-packages/alerta/webhooks/custom.py", line 66, in custom
     raise ApiError(str(e), 500)
alerta.exceptions.ApiError: cannot cast type record to history
LINE 10: ...new', '2020-10-05T09:14:05.934Z'::timestamp, NULL)::history]...
```
Unfortunately enabling DEBUG does not output what request was actually received, so i can't tell what the difference is :(

I hope you have an idea?

**Environment**
- OS: Linux (inside official docker image)
- API version: 8.0.2
- Deployment: Docker
- Database: Postgres
- Server config:
  Auth enabled? No
  Customer views? No

- web UI version: 8.0.2
- CLI version: 8.0.2

**Comment by KlavsKlavsen** [comment]
Doh.. accidently reverted to 7.5.1.. sigh.
