### ISSUE TITLE
Login not possible when using dex with multiple connectors

### ISSUE THREAD

**Issue by headnick23** [alerta/alerta#1336]
**Issue Summary**

Hi,
we enabled the openid auth provider and configured it to use dex as openid provider.

Dex is a federated openid provider and we enabled 2 connectors on it(ldap,microsoft)
We could login through dex using the microsoft federated connector, a user is created, and we are able to logout and login again using the same federated connector in dex.

But if we try to login through dex using a different connector(ldap), we get an exception from alerta

```
Oct 15 10:45:04 influx alertad[28913]: 2020-10-15 10:45:04,542 alerta.app[28919]: [ERROR] duplicate key value violates unique constraint "users_email_key"
                                       DETAIL:  Key (email)=(xxxxxx@xxxxx) already exists.
                                        request_id=7f8eab74-9c03-4d36-a92f-c5c0d82b3c6f ip=80.120.197.114
                                       Traceback (most recent call last):
                                         File "/opt/alerta/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
                                           rv = self.dispatch_request()
                                         File "/opt/alerta/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
                                           return self.view_functions[rule.endpoint](**req.view_args)
                                         File "/opt/alerta/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
                                           resp = make_response(f(*args, **kwargs))
                                         File "/opt/alerta/lib/python3.7/site-packages/alerta/auth/oidc.py", line 135, in openid
                                           user.create()
                                         File "/opt/alerta/lib/python3.7/site-packages/alerta/models/user.py", line 140, in create
                                           return User.from_db(db.create_user(self))
                                         File "/opt/alerta/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py", line 910, in create_user
                                           return self._insert(insert, vars(user))
                                         File "/opt/alerta/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py", line 1389, in _insert
                                           cursor.execute(query, vars)
                                         File "/opt/alerta/lib/python3.7/site-packages/psycopg2/extras.py", line 327, in execute
                                           return super(NamedTupleCursor, self).execute(query, vars)
                                       psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "users_email_key"
                                       DETAIL:  Key (email)=(xxxxxx@xxxxxxxx) already exists.
Oct 15 10:45:04 influx alertad[28913]: 2020-10-15 10:45:04,541 alerta.app[28919]: [DEBUG] ****************************************

                                                   INSERT INTO users (id, name, login, password, email, status, roles, attributes,
                                                       create_time, last_login, text, update_time, email_verified)
                                                   VALUES ('Cil1aWQ9c2hlZGVuaWdnLG91PVBlb3BsZSxkYz1pbnZlbml1bSxkYz1pbxIEbGRhcA', 'xxxxxxx', 'xxxxxxxxx', '', 'xxxxxxxxxx', 'active', ARRAY['admin']
                                                       NULL, '', '2020-10-15T10:45:04.541Z', true)
                                                   RETURNING *

                                       **************************************** request_id=7f8eab74-9c03-4d36-a92f-c5c0d82b3c6f ip=xxxxx
Oct 15 10:45:04 influx alertad[28913]: 2020-10-15 10:45:04,540 alerta.app[28919]: [DEBUG] ****************************************
                                       SELECT * FROM users WHERE id='Cil1aWQ9c2hlZGVuaWdnLG91PVBlb3BsZSxkYz1pbnZlbml1bSxkYz1pbxIEbGRhcA'
                                       **************************************** request_id=7f8eab74-9c03-4d36-a92f-c5c0d82b3c6f ip=xxxxx

```
The problem is that dex includes the provider when calculating the tokens sub claim, resulting in different sub claims depending on the federated connector used and as alerta uses the sub claim as userid and as search criteria it tries to create a new user with the same email address which produces the error.

I think the solution could be to just use the users email when checking if the user exists in the openid auth module !?

**Environment**
- OS: Linux(Debain 10)
- API version: 8.0.3
- Deployment: self-hosted
- WSGI environment: nginx/uwsgi

- Database: Postgres

- Server config:
 Auth enabled? Yes
 Auth provider? OpenID
 Customer views? No
 
- CLI version: 8.0.0

**Comment by satterly** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [contributed PRs fail tests because of github action docker permissions](https://trello.com/c/yCMW4GWc/610-contributed-prs-fail-tests-because-of-github-action-docker-permissions)
