### ISSUE TITLE
new LDAP filtering fails in odd way

### ISSUE THREAD

**Issue by KlavsKlavsen** [alerta/alerta#1373]
**Issue Summary**
If I have these settings for LDAP:
```
  LDAP_URL: "'ldaps://b00011.example.dk:636'"
  LDAP_BASEDN: "'DC=b00011,DC=example,DC=dk'"
```
- Login works just fine.

If I then try to switch to the new features, by setting:
```
LDAP_BIND_USERNAME: "'cn=APIMADLookup,OU=Example Users,DC=b00011,DC=example,DC=dk'"
LDAP_BIND_PASSWORD: "'Mysecretpass'"
LDAP_USER_FILTER: "'(&(objectCategory=person)(sAMAccountName={username}))'"
LDAP_USER_BASEDN: "'DC=b00011,DC=example,DC=dk'"
LDAP_USER_NAME_ATTR: "'cn'"
LDAP_USER_EMAIL_ATTR: "'mail'"
LDAP_GROUP_FILTER: "'(&(objectClass=group)(member={userdn}))'"
LDAP_DEFAULT_DOMAIN: "'example.dk'"
ALLOWED_LDAP_GROUPS: "['CN=API_COE_UDV_VIEW,OU=Example Groups,DC=b00011,DC=example,DC=dk']"
ALLOWED_EMAIL_DOMAINS: "['example.dk']"
```
But as soon as it tries to search (line 87 in auth/basic_ldap.py) - it fails saying you need to be authenticated first (on ldap connection).

If I then unset the LDAP_BIND_USERNAME - it skips that and instead fails on line 137 - where it should have done a bind with as the user trying to login - and outputs no failures to say otherwise, but on line 137 it then fails with the same LDAP error about one needing to be logged in first.

I haven't got a good idea on how to approach debugging this.. setting DEBUG: True - does not add anything relevant unfortunately ::(

ideas? 

**Environment**
- OS: Linux
- API version: 8.1.0
- Deployment: docker in Kubernetes
- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? No
- web UI version: 8.0.1

**Comment by KlavsKlavsen** [comment]
Above is the helm values - which has " and then ' - to end up with ' around them in configmap, which is necessary.

**Comment by satterly** [comment]
Can you include the exact debug log output? It would help a lot. Redact what you need to. Thanks.

**Comment by proffust** [comment]
settings:

```
LDAP_URL = 'ldap://sys.local:389'  # eg. ldap://localhost:389
LDAP_BASEDN = 'DC=sys,DC=local'
LDAP_DOMAINS = {
    'sys.local': 'sAMAccountName=%s'
}
LDAP_BIND_USERNAME = 'CN=grafana_ldap,OU=ServiceAccounts,OU=org,DC=sys,DC=local'  # required if using LDAP_SEARCH_QUERY eg. uid=admin,ou=users,dc=domain,dc=com
LDAP_BIND_PASSWORD = 'bid_password'  # required if using LDAP_BIND_USERNAME
LDAP_USER_FILTER = '(&(sAMAccountName={username}))'
LDAP_USER_BASEDN = 'DC=sys,DC=local'
LDAP_USER_NAME_ATTR = 'cn'
LDAP_USER_EMAIL_ATTR = 'mail'
LDAP_GROUP_FILTER = '(&(objectClass=group)(member={userdn}))'
LDAP_DEFAULT_DOMAIN = 'sys.local'
ALLOWED_LDAP_GROUPS = ['*']

```

in logs
```
2020-11-17 18:22:33,579 DEBG 'uwsgi' stdout output:
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7f9d1c3f2c10> ldap://sys.local:389 - SimpleLDAPObject.set_option
((17, 3), {})
=> result:
None
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7f9d1c3f2c10> ldap://sys.local:389 - SimpleLDAPObject.simple_bind
(('CN=grafana_ldap,OU=ServiceAccounts,OU=org,DC=sys,DC=local',
  'bind_password',
  None,
  None),
 {})

2020-11-17 18:22:33,579 DEBG 'uwsgi' stdout output:
=> result:
1
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7f9d1c3f2c10> ldap://sys.local:389 - SimpleLDAPObject.result4
((1, 1, -1, 0, 0, 0), {})

2020-11-17 18:22:33,587 DEBG 'uwsgi' stdout output:
=> result:
(97, [], 1, [])
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7f9d1c3f2c10> ldap://sys.local:389 - SimpleLDAPObject.search_ext
(('DC=sys,DC=local',
  2,
  '(&(objectCategory=person)(sAMAccountName=denis.ustinov))',
  ['cn', 'mail'],
  0,
  None,
  None,
  -1,
  0),
 {})
=> result:
2
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7f9d1c3f2c10> ldap://sys.local:389 - SimpleLDAPObject.result4
((2, 1, -1, 0, 0, 0), {})

2020-11-17 18:22:33,802 DEBG 'uwsgi' stdout output:
=> LDAPError - OPERATIONS_ERROR: {'msgtype': 100, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C0907B7, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v23f0'}

2020-11-17 18:22:33,805 DEBG 'uwsgi' stdout output:
2020-11-17 18:22:33,802 alerta.app[37]: [ERROR] {'msgtype': 100, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C0907B7, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v23f0'} request_id=833f883c-3799-44d4-a0f8-042f342c9927 ip=10.5.18.7
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/venv/lib/python3.7/site-packages/alerta/auth/login.py", line 12, in login
    return basic_ldap.login()
  File "/venv/lib/python3.7/site-packages/alerta/auth/basic_ldap.py", line 87, in login
    attrlist=user_attrs
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 870, in search_s
    return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 864, in search_ext_s
    return self.result(msgid,all=1,timeout=timeout)[1]
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 756, in result
    resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 760, in result2
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 767, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 774, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 340, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/venv/lib/python3.7/site-packages/ldap/compat.py", line 46, in reraise
    raise exc_value
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 324, in _ldap_call
    result = func(*args,**kwargs)
ldap.OPERATIONS_ERROR: {'msgtype': 100, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C0907B7, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v23f0'}

```

**Comment by KlavsKlavsen** [comment]
Thank you @proffust - I'm happy someone else also has this issue.. I've been fighting with other issues on a short deadline - so haven't had the time to capture in my annoying test environment (kubernetes only)

**Comment by KlavsKlavsen** [comment]
Its insanely odd - and since its all ldaps I haven't found a good way to see the ldap communication ( I don't have the server cert so I can decrypt the tls tunnel traffic) - to figure out why it goes wrong with the login the step previous - without failing in python.
And exact same user+pass works in grafana just fine.

**Comment by satterly** [comment]
What if we increased the log level? -1?

```
loglevel | Logging description
-- | --
-1 | enable all debugging
0 | no debugging
1 | trace function calls
2 | debug packet handling
4 | heavy trace debugging
8 | connection management
16 | print out packets sent and received
32 | search filter processing
64 | configuration file processing
128 | access control list processing
256 | stats log connections/operations/results
512 | stats log entries sent
1024 | print communication with shell backends
2048 | print entry parsing debugging
```

**Comment by proffust** [comment]
> What if we increased the log level? -1?
> 
> ```
> loglevel | Logging description
> -- | --
> -1 | enable all debugging
> 0 | no debugging
> 1 | trace function calls
> 2 | debug packet handling
> 4 | heavy trace debugging
> 8 | connection management
> 16 | print out packets sent and received
> 32 | search filter processing
> 64 | configuration file processing
> 128 | access control list processing
> 256 | stats log connections/operations/results
> 512 | stats log entries sent
> 1024 | print communication with shell backends
> 2048 | print entry parsing debugging
> ```

2020-11-18 11:54:18,620 alerta.app[42]: [ERROR] {'msgtype': 100, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C090A7D, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839'} request_id=b23d648a-882c-4b5f-b63f-d55e818eacc8 ip=10.5.18.7
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/venv/lib/python3.7/site-packages/alerta/auth/login.py", line 12, in login
    return basic_ldap.login()
  File "/venv/lib/python3.7/site-packages/alerta/auth/basic_ldap.py", line 87, in login
    attrlist=user_attrs
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 870, in search_s
    return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 864, in search_ext_s
    return self.result(msgid,all=1,timeout=timeout)[1]
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 756, in result
    resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 760, in result2
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 767, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 774, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 340, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/venv/lib/python3.7/site-packages/ldap/compat.py", line 46, in reraise
    raise exc_value
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 324, in _ldap_call
    result = func(*args,**kwargs)
ldap.OPERATIONS_ERROR: {'msgtype': 100, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C090A7D, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839'}

**Comment by satterly** [comment]
I assume you changed the log level for python-ldap but you have only included the python output. What about all the LDAP debug output that should have been displayed like in your previous comment? But more?!

**Comment by proffust** [comment]
> I assume you changed the log level for python-ldap but you have only included the python output. What about all the LDAP debug output that should have been displayed like in your previous comment? But more?!

```
2020-11-18 12:05:46,293 DEBG 'uwsgi' stdout output:
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7f12feb3a6d0> ldap://sys.local:389 - SimpleLDAPObject.set_option
((17, 3), {})
=> result:
None

2020-11-18 12:05:46,294 DEBG 'uwsgi' stdout output:
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7f12feb3a6d0> ldap://sys.local:389 - SimpleLDAPObject.simple_bind
(('CN=grafana_ldap,OU=ServiceAccounts,OU=org,DC=sys,DC=local',
  'YIP@$#9k5PJNASy',
  None,
  None),
 {})

2020-11-18 12:05:46,294 DEBG 'uwsgi' stdout output:
=> result:
1
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7f12feb3a6d0> ldap://sys.local:389 - SimpleLDAPObject.result4
((1, 1, -1, 0, 0, 0), {})

2020-11-18 12:05:46,298 DEBG 'uwsgi' stdout output:
=> result:
(97, [], 1, [])
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7f12feb3a6d0> ldap://sys.local:389 - SimpleLDAPObject.search_ext
(('DC=sys,DC=local',
  2,
  '(&(sAMAccountName=denis.ustinov))',
  ['cn', 'mail'],
  0,
  None,
  None,
  -1,
  0),
 {})

2020-11-18 12:05:46,298 DEBG 'uwsgi' stdout output:
=> result:
2
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7f12feb3a6d0> ldap://sys.local:389 - SimpleLDAPObject.result4
((2, 1, -1, 0, 0, 0), {})

2020-11-18 12:05:46,663 DEBG 'uwsgi' stdout output:
=> LDAPError - OPERATIONS_ERROR: {'msgtype': 100, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C090A69, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563'}
2020-11-18 12:05:46,660 alerta.app[41]: [ERROR] {'msgtype': 100, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C090A69, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563'} request_id=3ec5429b-2084-4597-adb3-ebc174aed829 ip=10.5.18.7
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/venv/lib/python3.7/site-packages/alerta/auth/login.py", line 12, in login
    return basic_ldap.login()
  File "/venv/lib/python3.7/site-packages/alerta/auth/basic_ldap.py", line 87, in login
    attrlist=user_attrs
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 870, in search_s
    return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 864, in search_ext_s
    return self.result(msgid,all=1,timeout=timeout)[1]
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 756, in result
    resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 760, in result2
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 767, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 774, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 340, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/venv/lib/python3.7/site-packages/ldap/compat.py", line 46, in reraise
    raise exc_value
  File "/venv/lib/python3.7/site-packages/ldap/ldapobject.py", line 324, in _ldap_call
    result = func(*args,**kwargs)
ldap.OPERATIONS_ERROR: {'msgtype': 100, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C090A69, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563'}

2020-11-18 12:05:46,668 DEBG 'uwsgi' stdout output:
[pid: 41|app: 0|req: 18/68] 172.18.0.7 () {54 vars in 862 bytes} [Wed Nov 18 12:05:46 2020] POST /api/auth/login => generated 2706 bytes in 377 msecs (HTTP/1.0 500) 3 headers in 144 bytes (1 switches on core 0)

```

**Comment by proffust** [comment]
settings
```
LOG_LEVEL = -1
DEBUG=True
AUTH_REQUIRED=False
AUTH_PROVIDER=ldap

```

**Comment by satterly** [comment]
No. That's not what I had in mind. To change the log level for python-ldap would require a code change.

**Comment by satterly** [comment]
I think it better to continue this on Slack until we have a resolution. These backwards-and-forwards comments in a GitHub issue is just creating noise. Please join if you haven't already at https://slack.alerta.dev

**Comment by satterly** [comment]
Closing due to inactivity. If this is still an issue, please reopen with details.
