### ISSUE TITLE
Support for MongoDB 4.4

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#1376]
Verify support for MongoDB 4.4.

Aug 31 07:19
Hi, all. First time trying out Alerta and trying to run it in a docker container on windows running WSL2 and following instructions here and here. Once I start the alerta-web container and tail its logs, I'm seeing this error:
mounting wsgi:app on /api

2020-08-31 05:02:09,649 DEBG 'uwsgi' stdout output:
Traceback (most recent call last):
  File "./wsgi.py", line 2, in <module>

2020-08-31 05:02:09,649 DEBG 'uwsgi' stdout output:
    app = create_app()
  File "/venv/lib/python3.7/site-packages/alerta/app.py", line 67, in create_app
    db.init_db(app)
  File "/venv/lib/python3.7/site-packages/alerta/database/base.py", line 47, in init_db
    self.create_engine(app, uri=app.config['DATABASE_URL'], dbname=app.config['DATABASE_NAME'])
  File "/venv/lib/python3.7/site-packages/alerta/database/backends/mongodb/base.py", line 26, in create_engine
    self._create_indexes(db)
  File "/venv/lib/python3.7/site-packages/alerta/database/backends/mongodb/base.py", line 43, in _create_indexes

2020-08-31 05:02:09,649 DEBG 'uwsgi' stdout output:
    db.customers.drop_indexes()  # FIXME: should only drop customers index if it's unique (ie. the old one)
  File "/venv/lib/python3.7/site-packages/pymongo/collection.py", line 2060, in drop_indexes

2020-08-31 05:02:09,649 DEBG 'uwsgi' stdout output:
    self.drop_index("*", session=session, **kwargs)
  File "/venv/lib/python3.7/site-packages/pymongo/collection.py", line 2116, in drop_index

2020-08-31 05:02:09,650 DEBG 'uwsgi' stdout output:
    session=session)
  File "/venv/lib/python3.7/site-packages/pymongo/collection.py", line 250, in _command

2020-08-31 05:02:09,650 DEBG 'uwsgi' stdout output:
    user_fields=user_fields)
  File "/venv/lib/python3.7/site-packages/pymongo/pool.py", line 613, in command

2020-08-31 05:02:09,650 DEBG 'uwsgi' stdout output:
    user_fields=user_fields)
  File "/venv/lib/python3.7/site-packages/pymongo/network.py", line 167, in command

2020-08-31 05:02:09,650 DEBG 'uwsgi' stdout output:
    parse_write_concern_error=parse_write_concern_error)
  File "/venv/lib/python3.7/site-packages/pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: ns not found monitoring.customers
unable to load app 0 (mountpoint='/api') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
It looks like the MongoDB setup script is trying to drop indexes that don't exist yet which then causes the rest of the script to fail? If I try to connect to the endpoint I get a failure to connect to Alerta API error due to missing or invalid config.json file. Lines 43 and 48 in /venv/lib/python3.7/site-packages/alerta/database/backends/mongodb/base.py seem to be the culprits of the errors above so I tried to figure out the syntax for catching the error but eventually I just commented out those lines completely. After restarting the container, I can hit the web UI and begin configuration like normal. I'm guessing this isn't normal behavior though, right? This isn't a config file you would normally need to touch right out of the box is it?
Siva Paramasivam

Siva Paramasivam
@apsivam
Aug 31 08:15
Looks like you are facing the same problem as me.
Siva Paramasivam

Siva Paramasivam
@apsivam
Aug 31 08:15
I started with latest version Mongo and got this error then downgraded to Mongo 3
kendr1ck

kendr1ck
@kendr1ck
Aug 31 10:42
glad to hear it's not me. already down another rabbit hole right now but i'll try it with the downgraded version of Mongo and report back

**Comment by satterly** [comment]
Build and test pipeline runs against mongo latest docker container which as of now is version 4.4.1.
