### ISSUE TITLE
User-defined exceptions raised in plugins should not be 500 errors

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#1378]
Howie
@wo250012
20:40
I have a request to implement some functionality in Alerta that would prevent someone from manually clearing a certain type of alert. This will most likely be based on alert origin (the criteria is not the issue). My question is what would be the best way to actually prevent clearing? I am thinking I could throw an exception in a plugin that would cause an HTTP error so that it shows up in the UI. Anyone have any thoughts on this?
Howie

Howie
@wo250012
21:40
I tried a raise ApiError('Not allowed to close alert', 400) but the actual error in the UI comes across as a 500 error from the plugin, so I don't think I am raising this properly. This does seem to work in webhooks though. @satterly, let me know if I am doing this properly.
Nick Satterly

Nick Satterly
@satterly
21:40
i wouldn’t throw an ApiError
Nick Satterly

Nick Satterly
@satterly
21:41
you could throw InvalidAction https://github.com/alerta/alerta/blob/master/alerta/exceptions.py#L41
Howie

Howie
@wo250012
21:42
great, thanks much.
Howie

Howie
@wo250012
21:42
BTW, thanks for all the work recently on Alerta. It is very much appreciated.
Howie

Howie
@wo250012
21:46
hmm...It still seems to be throwing a plugin 500 too: "Error while running action plugin 'prevent_clearing': Not allowed to close alert (500)"
Howie

Howie
@wo250012
21:46
or maybe that is expected? I was hoping to throw an error in the UI without having it show up as an exception in the logs
Nick Satterly

Nick Satterly
@satterly
21:52
InvalidAction should generate a 409 Conflict response https://github.com/alerta/alerta/blob/master/alerta/views/alerts.py#L162-L163
Howie

Howie
@wo250012
21:53
here is the plugin code:
   def take_action(self, alert, action, text, **kwargs):

        if action == 'close' and alert.origin == 'dtsaas':
            raise InvalidAction('Not allowed to close alert')

        return alert
Howie

Howie
@wo250012
22:02
Here are the errors in the logs:
2020-11-10 13:00:13,548 - alerta.app[56747]: ERROR - Error while running action plugin 'prevent_clearing': Not allowed to close alert [in /opt/alerta/lib64/python3.6/site-packages/alerta/exceptions.py:99]
Traceback (most recent call last):
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/utils/api.py", line 97, in process_action
    updated = plugin.take_action(alert, action, text, timeout=timeout, config=wanted_config)
  File "/opt/alerta/lib64/python3.6/site-packages/prevent_clearing-0.0.1-py3.6.egg/prevent_clearing.py", line 35, in take_action
    raise InvalidAction('Not allowed to close alert')
alerta.exceptions.InvalidAction: Not allowed to close alert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/views/alerts.py", line 155, in action_alert
    alert, action, text, timeout = process_action(alert, action, text, timeout)
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/utils/api.py", line 104, in process_action
    raise ApiError("Error while running action plugin '{}': {}".format(plugin.name, str(e)))
alerta.exceptions.ApiError: Error while running action plugin 'prevent_clearing': Not allowed to close alert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/alerta/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/alerta/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/alerta/lib64/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/auth/decorators.py", line 89, in wrapped
    return f(*args, **kwargs)
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/models/metrics.py", line 258, in wrapped
    response = f(*args, **kwargs)
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/utils/response.py", line 18, in decorated
    return func(*args, **kwargs)
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/views/alerts.py", line 167, in action_alert
    raise ApiError(str(e), 500)
alerta.exceptions.ApiError: Error while running action plugin 'prevent_clearing': Not allowed to close alert
2020-11-10 13:00:13,549 - alerta.app[56748]: ERROR - Error while running action plugin 'prevent_clearing': Not allowed to close alert [in /opt/alerta/lib64/python3.6/site-packages/alerta/exceptions.py:99]
Traceback (most recent call last):
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/utils/api.py", line 97, in process_action
    updated = plugin.take_action(alert, action, text, timeout=timeout, config=wanted_config)
  File "/opt/alerta/lib64/python3.6/site-packages/prevent_clearing-0.0.1-py3.6.egg/prevent_clearing.py", line 35, in take_action
    raise InvalidAction('Not allowed to close alert')
alerta.exceptions.InvalidAction: Not allowed to close alert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/views/alerts.py", line 155, in action_alert
    alert, action, text, timeout = process_action(alert, action, text, timeout)
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/utils/api.py", line 104, in process_action
    raise ApiError("Error while running action plugin '{}': {}".format(plugin.name, str(e)))
alerta.exceptions.ApiError: Error while running action plugin 'prevent_clearing': Not allowed to close alert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/alerta/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/alerta/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
Nick Satterly

Nick Satterly
@satterly
22:10
ok the log doesn’t look great but what does the HTTP response look like?
Howie

Howie
@wo250012
22:12
the msg in the ui is this: Error while running action plugin 'prevent_clearing': Not allowed to close alert (500)
Howie

Howie
@wo250012
22:13
here is what is in the dev console:
{
  "code": 500, 
  "errors": null, 
  "message": "Error while running action plugin 'prevent_clearing': Not allowed to close alert", 
  "requestId": null, 
  "status": "error"
}
Nick Satterly

Nick Satterly
@satterly
23:10
not sure why it’s a 500. will need to check that.

**Comment by satterly** [comment]
Now you can do ..
```
    def take_action(self, alert, action, text, **kwargs):

        if action == 'invalid':
            raise InvalidAction('{} is not a valid action for this status'.format(action))
```
... and it will return a HTTP 409 status code, instead of a 500 server error.
