### ISSUE TITLE
'NoneType' object is not subscriptable exception from housekeeping

### ISSUE THREAD

**Issue by 3IMOH** [alerta/alerta#1416]
I am seeing this exception when my housekeeping job runs (every 2 min). I am looking for any alerts that may be causing this but have not found it yet.

2020-12-09 06:10:02,972 - alerta.app[38174]: ERROR - 'NoneType' object is not subscriptable [in /opt/alerta/lib64/python3.6/site-packages/alerta/exceptions.py:99]
Traceback (most recent call last):
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/management/views.py", line 157, in housekeeping
    alert = alert.from_expired(text, timeout)
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/models/alert.py", line 643, in from_expired
    return self.from_action(action='expired', text=text, timeout=timeout)
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/models/alert.py", line 609, in from_action
    r = status_change_hook.send(self, status=new_status, text=text)
  File "/opt/alerta/lib64/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/opt/alerta/lib64/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/utils/hooks.py", line 45, in process_status_change
    alert.attributes = alert.update_attributes(alert.attributes)
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/models/alert.py", line 452, in update_attributes
    return db.update_attributes(self.id, self.attributes, attributes)
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/database/backends/mongodb/base.py", line 432, in update_attributes
    )['attributes']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/alerta/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/alerta/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/alerta/lib64/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/auth/decorators.py", line 53, in wrapped
    return f(*args, **kwargs)
  File "/opt/alerta/lib64/python3.6/site-packages/alerta/management/views.py", line 165, in housekeeping
    raise ApiError(str(e), 500)
alerta.exceptions.ApiError: 'NoneType' object is not subscriptable

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by satterly** [comment]
Closing due to inactivity. If you believe this issue has been closed prematurely please provide more information to help progress the issue. If you do not know what is expected you can ask on [Slack](https://slack.alerta.dev).
