### ISSUE TITLE
Customer views - can't see alarms - NoCustomerMatch - postgres

### ISSUE THREAD

**Issue by CWollinger** [alerta/alerta#1465]
**Issue Summary**
Unable to see alerts with Customer views. 

**Environment**
- OS: Linux with Docker
- API version: 8.3.3
- Deployment: Docker

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? Yes

- web UI version: 8.4.0
- CLI version: 8.3.0

**To Reproduce**
1. Send alarm from alertmanager to alerta with labels customer
2. Login as admin

Can't see an alarm. 
Error in alertmanager: ``unexpected status code 500`` towards alerta API

**Expected behavior**
See all alarms from all customers as admin.

**Additional context**
Error in alerta:
````
2021-02-16 11:50:25,192 alerta.app[49]: [ERROR] sequence item 0: expected str instance, NoneType found request_id=8beb6677-3b81-432f-8eeb-f6f6e6bc4700 ip=192.168.136.1
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/venv/lib/python3.7/site-packages/alerta/auth/decorators.py", line 114, in wrapped
    g.customers = get_customers(user.email, groups=[user.domain])
  File "/venv/lib/python3.7/site-packages/alerta/auth/utils.py", line 42, in get_customers
    return Customer.lookup(login, groups)
  File "/venv/lib/python3.7/site-packages/alerta/models/customer.py", line 82, in lookup
    customers = db.get_customers_by_match(login, matches=groups)
  File "/venv/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py", line 1238, in get_customers_by_match
    raise NoCustomerMatch("No customer lookup configured for user '{}' or '{}'".format(login, ','.join(matches)))
TypeError: sequence item 0: expected str instance, NoneType found
````

**Comment by CWollinger** [comment]
Update:

This only appears when I use basic auth in alertmanager. Not, if I use an API key for the alerta webhook URL

**Comment by satterly** [comment]
Did you define any customer lookups?

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Slack](https://slack.alerta.dev).

**Comment by satterly** [comment]
Closing due to inactivity. If you believe this issue has been closed prematurely please provide more information to help progress the issue. If you do not know what is expected you can ask on [Slack](https://slack.alerta.dev).
