### ISSUE TITLE
Werkzeug 2.0.0 broke Alerta

### ISSUE THREAD

**Issue by Samgarr** [alerta/alerta#1527]
**Issue Summary**

```
mounting wsgi.py on /api
Traceback (most recent call last):
  File "wsgi.py", line 1, in <module>
    from alerta import create_app
  File "/usr/local/lib/python3.7/dist-packages/alerta/__init__.py", line 28, in <module>
    from .app import create_app  # noqa isort:skip
  File "/usr/local/lib/python3.7/dist-packages/alerta/app.py", line 4, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.7/dist-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 19, in <module>
    from werkzeug.local import ContextVar
ImportError: cannot import name 'ContextVar' from 'werkzeug.local' (/usr/local/lib/python3.7/dist-packages/werkzeug/local.py)
```

**Environment**
- OS: linux
- API version: 8.3.3
- Deployment: self-hosted
- For self-hosted, WSGI environment:nginx/uwsgi

- Database: mongodb

- web UI version: 8.4.0
- CLI version: 8.3.0

**To Reproduce**
1. install Alerta via pip

**Comment by satterly** [comment]
What was the exact command you ran? `pip install alerta-server` or did you clone the repo and run `pip install .` or `pip install -r requirements.txt` ?

**Comment by Samgarr** [comment]
`pip3 install alerta-server`
But nevermind, looks like i had installed werzeug=2.0.0 manually before running `pip3 install alerta-server` which causing this troube. After uninstalling werzeug running again `pip3 install alerta-server` is everything fine. Sorry for making noise :)
