### ISSUE TITLE
alertad run failed

### ISSUE THREAD

**Issue by zh355245849** [alerta/alerta#1544]
Could some one help me figure out why I can't run the server success? Thanks.
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Issue Summary**

**Environment**
- OS: Windows
- API version: windows10, pyhon3.9
- Deployment: self-hosted
- For self-hosted, WSGI environment: windows10

- Database: MongoDB

- Server config:
  Auth enabled? No

- web UI version: Alerta Web UI 7.0
**To Reproduce**
1. Go to cmd, pip install alerta-server alerta
2. Run alertad run
3. Scroll down to bottom
4. See error (include command output)

**Expected behavior**
it should start server success with message listen port on xxxx

**Screenshots**
![image](https://user-images.githubusercontent.com/11755918/121510023-cac78a80-ca19-11eb-823b-440e4606061b.png)

**Additional context**
alertad run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\logging\config.py", line 564, in configure
    handler = self.configure_handler(handlers[name])
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\logging\config.py", line 745, in configure_handler
    result = factory(**kwargs)
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\logging\handlers.py", line 153, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\logging\handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\dev\\null'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\zhanha\AppData\Local\Programs\Python\Python39\Scripts\alertad.exe\__main__.py", line 7, in <module>
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 305, in __init__
    self._load_unlocked()
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 381, in load_app
    app = call_factory(self, self.create_app)
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 119, in call_factory
    return app_factory()
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\alerta\app.py", line 54, in create_app
    logger.setup_logging(app)
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\site-packages\alerta\utils\logging.py", line 43, in setup_logging
    dictConfig({
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\logging\config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "c:\users\zhanha\appdata\local\programs\python\python39\lib\logging\config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'

**Comment by zh355245849** [comment]
it seems this value LOG_CONFIG_FILE not set in the alerta server

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Slack](https://slack.alerta.dev).

**Comment by satterly** [comment]
Windows is not supported. However, you could try setting `LOG_FILE` in the `alertad.conf` configuration file.

**Comment by zh355245849** [comment]
> Windows is not supported. However, you could try setting `LOG_FILE` in the `alertad.conf` configuration file.

hi, stately, I use my mac to setup but occur this message when I try start alerta server 
TypeError: 'ScriptInfo' object is not iterable, could you guide me to the correct path? Thanks again!

**Comment by satterly** [comment]
You haven't provided any of your configuration files so no, I can't help you unless you do.

**Comment by satterly** [comment]
What's the output of `pip3 list`?

**Comment by 3IMOH** [comment]
Closing due to lack of response...please reopen with more info if you have it.
