### ISSUE TITLE
History API reference lacks documentation on params or certain params are broken

### ISSUE THREAD

**Issue by w4tsn** [alerta/alerta#1552]
**Issue Summary**
I'm using the HTTP API for retrieving alert history. The documentation states that any `<attr>` is supported as a query param / filter. From what I can tell, not all `<attr>` are supported or not all of them work. It's either a bug or shortcoming in the documentation.

The working params are `resource`, `environment`, `group`, and `origin`.

E.g. the `event` parameter returns a 500 server error stating that `column reference "event" is ambiguous`.

**Environment**
- OS: Linux
- API version: 8.5.0
- Deployment: docker+docker-compose

- Database: Postgres 13

- Server config:
  Auth enabled? Yes
  Auth provider? OpenID/Keycloak
  Customer views? No

- web UI version: 8.5.0
- CLI version: 8.5.0

**To Reproduce**

Execute an HTTP request against an alert with history. Use any supposedly unsupported query param.

**Expected behavior**
Either I expect the documentation to describe which attributes are supported or that all attributes work.

**Additional context**
I'm always setting at least either `environment` or `resource` additional to any other non-working request param.

**Error response from API**
```python
{
    'code': 500,
    'errors': ['Traceback (most recent call last):\n  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function\n    resp = make_response(f(*args, **kwargs))\n  File "/venv/lib/python3.7/site-packages/alerta/auth/decorators.py", line 53, in wrapped\n    return f(*args, **kwargs)\n  File "/venv/lib/python3.7/site-packages/alerta/models/metrics.py", line 258, in wrapped\n    response = f(*args, **kwargs)\n  File "/venv/lib/python3.7/site-packages/alerta/utils/response.py", line 18, in decorated\n    return func(*args, **kwargs)\n  File "/venv/lib/python3.7/site-packages/alerta/views/alerts.py", line 356, in history\n    history = Alert.get_history(query, paging.page, paging.page_size)\n  File "/venv/lib/python3.7/site-packages/alerta/models/alert.py", line 490, in get_history\n    return [RichHistory.from_db(hist) for hist in db.get_history(query, page, page_size)]\n  File "/venv/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py", line 502, in get_history\n    ) for h in self._fetchall(select, query.vars, limit=page_size, offset=(page - 1) * page_size)\n  File "/venv/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py", line 1590, in _fetchall\n    cursor.execute(query, vars)\n  File "/venv/lib/python3.7/site-packages/psycopg2/extras.py", line 327, in execute\n    return super(NamedTupleCursor, self).execute(query, vars)\npsycopg2.errors.AmbiguousColumn: column reference "event" is ambiguous\nLINE 6: AND "event"=\'property:features/LPBBoiler/properties/status/s...\n            ^\n\n'],
    'message': 'column reference "event" is ambiguous\nLINE 6: AND "event"=\'property:features/LPBBoiler/properties/status/s...\n            ^\n',
    'requestId': '3c882413-3b67-4b4b-a07b-01dca37a18c5',
    'status': 'error'
}
```

**Comment by satterly** [comment]
Closing due to inactivity. This is a documentation issue -- the history API filter parameters are not fully documented. If still relevant, please reopen or raise against the docs repo.
