### ISSUE TITLE
Prometheus severity=info causes exception

### ISSUE THREAD

**Issue by darkobas2** [alerta/alerta#1670]
**Issue Summary**

**Environment**
- OS: [Linux]
- API version: [eg. 8.7.0]
- Deployment: [Docker,  self-hosted]
- For self-hosted, WSGI environment: [eg. nginx/uwsgi]

- Database: [Postgres]

- Server config:
  Auth enabled? Yes
  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: [8.7.0]
- CLI version: [8.7.0]

**To Reproduce**

````
# curl -s -XPOST https://alerta/api/alert?api-key=demo-key -H 'Content-type: application/json' -d '{
      "attributes": {
        "region": "EU"
      },
      "correlate": [
        "HttpServerError",
        "HttpServerOK"
      ],
      "environment": "Production",
      "event": "HttpServerError",
      "group": "Web",
      "origin": "curl",
      "resource": "web01",
      "service": [
        "example.com"
      ],
      "severity": "info",
      "tags": [
        "dc1"
      ],
      "text": "Site is down.",
      "type": "exceptionAlert",
      "value": "Bad Gateway (501)"
    }' |jq
{
  "code": 500,
  "errors": null,
  "message": "Severity (info) is not one of security, critical, major, minor, warning, indeterminate, informational, normal, ok, cleared, debug, trace, unknown",
  "requestId": "10cfc86e-a6d6-4e7f-b734-54784acc4cd9",
  "status": "error"
}
````

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**

Severity=info is regulary used in ie. prometheus

**Additional context**
Log:
````
web_1        | 2022-01-28 15:52:04,449 DEBG 'nginx' stdout output:
web_1        | 172.20.0.1 - - [28/Jan/2022:15:52:04 +0000] "POST /api/webhooks/prometheus?api-key=lalalala HTTP/1.1" 500 253 "-" "Alertmanager/0.23.0" - 0.037 x_forwarded_for=- host=alerta cc3e65ecb1224f9015c6e5d2ecba65f7 0bf9f335-3cdc-4184-8f7f-999965754102
web_1        | 
web_1        | 2022-01-28 15:52:04,449 DEBG 'uwsgi' stdout output:
web_1        | 2022-01-28 15:52:04,444 alerta.app[24725]: [ERROR] Severity (info) is not one of security, critical, major, minor, warning, indeterminate, informational, normal, ok, cleared, debug, trace, unknown request_id=0bf9f335-3cdc-4184-8f7f-999965754102 ip=172.20.0.1
web_1        | Traceback (most recent call last):
web_1        |   File "/venv/lib/python3.8/site-packages/alerta/utils/api.py", line 63, in process_alert
web_1        |     alert = alert.create()
web_1        |   File "/venv/lib/python3.8/site-packages/alerta/models/alert.py", line 383, in create
web_1        |     _, self.status = alarm_model.transition(
web_1        |   File "/venv/lib/python3.8/site-packages/alerta/models/alarms/alerta.py", line 122, in transition
web_1        |     raise ApiError(f"Severity ({current_severity}) is not one of {', '.join(valid_severities)}", 400)
web_1        | alerta.exceptions.ApiError: Severity (info) is not one of security, critical, major, minor, warning, indeterminate, informational, normal, ok, cleared, debug, trace, unknown
web_1        | 
web_1        | During handling of the above exception, another exception occurred:
web_1        | 
web_1        | Traceback (most recent call last):
web_1        |   File "/venv/lib/python3.8/site-packages/alerta/webhooks/custom.py", line 55, in custom
web_1        |     alert = process_alert(alert)
web_1        |   File "/venv/lib/python3.8/site-packages/alerta/utils/api.py", line 65, in process_alert
web_1        |     raise ApiError(str(e))
web_1        | alerta.exceptions.ApiError: Severity (info) is not one of security, critical, major, minor, warning, indeterminate, informational, normal, ok, cleared, debug, trace, unknown
web_1        | 
web_1        | During handling of the above exception, another exception occurred:
web_1        | 
web_1        | Traceback (most recent call last):
web_1        |   File "/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
web_1        |     rv = self.dispatch_request()
web_1        |   File "/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
web_1        |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
web_1        |   File "/venv/lib/python3.8/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
web_1        |     resp = make_response(f(*args, **kwargs))
web_1        |   File "/venv/lib/python3.8/site-packages/alerta/auth/decorators.py", line 53, in wrapped
web_1        |     return f(*args, **kwargs)
web_1        |   File "/venv/lib/python3.8/site-packages/alerta/webhooks/custom.py", line 73, in custom
web_1        |     raise ApiError(str(e), 500)
web_1        | alerta.exceptions.ApiError: Severity (info) is not one of security, critical, major, minor, warning, indeterminate, informational, normal, ok, cleared, debug, trace, unknown
web_1        | 
````

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by darkobas2** [comment]
workarround is to rewrite the label in alertmanager

````
    additionalAlertRelabelConfigs:
        - source_labels:
            - severity
          action: replace
          regex: info
          replacement: "informational"
          target_label: severity
````

**Comment by darkobas2** [comment]
Same with severity="none" (Prometheus watchdog)

**Comment by lotooo** [comment]
Another solution is to allow `info` severity in your `SEVERITY_MAP`: 

```
SEVERITY_MAP = {
    'security': 0,
    'critical': 1,
    'major': 4,
    'minor': 4,
    'warning': 4,
    'info': 5,
    'informational': 5,
    'debug': 6,
    'trace': 7,
    'indeterminate': 8,
    'cleared': 9,
    'normal': 9,
    'ok': 9,
    'unknown': 10
}
```

**Comment by darkobas2** [comment]
nice, thanx!
