### ISSUE TITLE
can't push webhook cloudwatch 

### ISSUE THREAD

**Issue by linhnh90** [alerta/alerta#1744]
i try push webhook cloudwatch from sns but get error with arrgument 'path'
POST /api/webhooks/cloudwatch?api-key=demo-key HTTP/1.1
Host: 13.214.198.207:8080
x-amz-sns-message-type: SubscriptionConfirmation
x-amz-sns-message-id: 165545c9-2a5c-472c-8df2-7ff2be2b3b1b
x-amz-sns-topic-arn: arn:aws:sns:us-west-2:123456789012:MyTopic
Connection: Keep-Alive
User-Agent: Amazon Simple Notification Service Agent
Host: 13.214.198.207:8080
Authorization: Basic bGluaG5oOTA6aG9hbmdsaW5oOTA=
Content-Type: application/json
Content-Length: 925

{
  "Type" : "SubscriptionConfirmation",
  "MessageId" : "165545c9-2a5c-472c-8df2-7ff2be2b3b1b",
  "Token" : "2336412f37...",
  "TopicArn" : "arn:aws:sns:us-west-2:123456789012:MyTopic",
  "Message" : "You have chosen to subscribe to the topic arn:aws:sns:us-west-2:123456789012:MyTopic.\nTo confirm the subscription, visit the SubscribeURL included in this message.",
  "SubscribeURL" : "https://sns.us-west-2.amazonaws.com/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:us-west-2:123456789012:MyTopic&Token=2336412f37...",
  "Timestamp" : "2012-04-26T20:45:04.751Z",
  "SignatureVersion" : "1",
  "Signature" : "EXAMPLEpH+DcEwjAPg8O9mY8dReBSwksfg2S7WKQcikcNKWLQjwu6A4VbeS0QHVCkhRS7fUQvi2egU3N858fiTDN6bkkOxYDVrY0Ad8L10Hs3zH81mtnPk5uvvolIC1CXGu43obcgFxeL3khZl8IKvO61GWB6jI9b5+gLPoBc1Q=",
  "SigningCertURL" : "https://sns.us-west-2.amazonaws.com/SimpleNotificationService-f3ecfb7224c7233fe7bb5f59f96de52f.pem"
}

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/venv/lib/python3.8/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/venv/lib/python3.8/site-packages/alerta/auth/decorators.py", line 53, in wrapped
    return f(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/alerta/webhooks/custom.py", line 32, in custom
    rv = custom_webhooks.webhooks[webhook].incoming(
TypeError: incoming() missing 1 required positional argument: 'path'
kindly please guide me how to push path to api

**Comment by streaming-pete** [comment]
are you trying to get cloudwatch alerts -> sns -> alerta api? or send alerts from alerta into SNS?

**Comment by satterly** [comment]
Closing due to inactivity. If this is still an issue, please reopen with details.
