### ISSUE TITLE
getting Postgres error in alerta

### ISSUE THREAD

**Issue by sankhyan** [alerta/alerta#1783]
WEB UI version 8.0.1

i am getting below error while making alerta up, 

permissions to DB user used is the issue or something else? please help here using AWS RDS here with non admin user

error:-

2022-10-28 07:17:25,408 DEBG 'uwsgi' stdout output:
    app = create_app()
  File "/venv/lib/python3.7/site-packages/alerta/app.py", line 67, in create_app
    db.init_db(app)
  File "/venv/lib/python3.7/site-packages/alerta/database/base.py", line 47, in init_db
    self.create_engine(app, uri=app.config['DATABASE_URL'], dbname=app.config['DATABASE_NAME'])
  File "/venv/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py", line 77, in create_engine
    globally=True
  File "/venv/lib/python3.7/site-packages/psycopg2/extras.py", line 1158, in register_composite

2022-10-28 07:17:25,408 DEBG 'uwsgi' stdout output:
    caster = factory._from_db(name, conn_or_curs)
  File "/venv/lib/python3.7/site-packages/psycopg2/extras.py", line 1130, in _from_db

2022-10-28 07:17:25,408 DEBG 'uwsgi' stdout output:
    "PostgreSQL type '%s' not found" % name)

2022-10-28 07:17:25,408 DEBG 'uwsgi' stdout output:
psycopg2.ProgrammingError: PostgreSQL type 'history' not found
unable to load app 0 (mountpoint='') (callable not found or import error)
mounting wsgi:app on /api

2022-10-28 07:17:25,441 DEBG 'uwsgi' stdout output:
Traceback (most recent call last):

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Slack](https://slack.alerta.dev).

**Comment by satterly** [comment]
Closing due to inactivity. This appears to be a database permissions issue.
