### ISSUE TITLE
alerta top fails

### ISSUE THREAD

**Issue by arindamchoudhury** [alerta/alerta#454]
$ alerta top
Traceback (most recent call last):
  File "/usr/bin/alerta", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/alertaclient/commands/cmd_top.py", line 14, in cli
    screen.run()
  File "/usr/lib/python2.7/site-packages/alertaclient/top.py", line 24, in run
    wrapper(self.main)
  File "/usr/lib64/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python2.7/site-packages/alertaclient/top.py", line 66, in main
    self.update()
  File "/usr/lib/python2.7/site-packages/alertaclient/top.py", line 112, in update
    ), color(alert.severity))
  File "/usr/lib/python2.7/site-packages/alertaclient/top.py", line 127, in _addstr
    self.screen.addstr(y, x, str, attr)
_curses.error: addstr() returned ERR

**Comment by satterly** [comment]
Can you provide any more info? The traceback stops just as it was getting useful.
