### ISSUE TITLE
Utility method for plugins is_flapping() is broken

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#456]
```
2018-01-26 11:04:16,782 - alerta.plugins.flapping[9]: INFO - recieved exception [in /usr/local/lib/python3.6/site-packages/alerta_flapping-1.0.1-py3.6.egg/alerta_flapping.py:28]
2018-01-26 11:04:16,782 - alerta.plugins.flapping[9]: ERROR - A pipeline stage specification object must contain exactly one field. [in /usr/local/lib/python3.6/site-packages/alerta_flapping-1.0.1-py3.6.egg/alerta_flapping.py:29]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/alerta_flapping-1.0.1-py3.6.egg/alerta_flapping.py", line 14, in pre_receive
    result = alert.is_flapping(count=FLAPPING_COUNT, window=FLAPPING_WINDOW)
  File "/usr/local/lib/python3.6/site-packages/alerta/models/alert.py", line 223, in is_flapping
    return db.is_flapping(self, window, count)
  File "/usr/local/lib/python3.6/site-packages/alerta/database/backends/mongodb/base.py", line 144, in is_flapping
    responses = g.db.alerts.aggregate(pipeline)
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 2181, in aggregate
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 2088, in _aggregate
    client=self.__database.client)
  File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 496, in command
    collation=collation)
  File "/usr/local/lib/python3.6/site-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 146, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: A pipeline stage specification object must contain exactly one field.
```

@arindamchoudhury

**Comment by satterly** [comment]
When running MongoDB server version: 3.4.10

**Comment by arindamchoudhury** [comment]
also with MongoDB server version: 3.6.2
