### ISSUE TITLE
timeout errors

### ISSUE THREAD

**Issue by arindamchoudhury** [alerta/alerta#459]
$ alerta ack -i 5e3db307-5cd1-49f5-8eb4-16aa801d96fe
Acking 1 alerts  [####################################]  100%
Traceback (most recent call last):
  File "/usr/bin/alerta", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/alertaclient/commands/cmd_ack.py", line 23, in cli
    client.set_status(id, status='ack', text=text or 'status changed using CLI')
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 80, in set_status
    return self.http.put('/alert/%s/status' % id, data)
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 317, in put
    response = self.session.put(url, data=json.dumps(data, cls=CustomJsonEncoder), headers=headers, auth=self.auth, timeout=self.timeout)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 566, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='alerta.server.com', port=443): Read timed out. (read timeout=5.0)

**Comment by arindamchoudhury** [comment]
very frequent with postgres backend and master branch. occasional when using mongodb and v5.0.5.

**Comment by arindamchoudhury** [comment]
it happens if I compile grpcio
pip install grpcio --ignore-installed --no-binary grpcio

**Comment by satterly** [comment]
the timeout errors happens if i compile grpcio pip install grpcio --ignore-installed --no-binary grpcio

**Comment by satterly** [comment]
@arindamchoudhury how many alerts do you have in the database?

Did you know you can set the timeout to different value that is more suited to your environment?
See the "timeout" setting for `alerta` CLI here  http://docs.alerta.io/en/latest/cli.html#configuration

**Comment by satterly** [comment]
@arindamchoudhury if this is a problem with grpcio then I this isn't something I can fix. Please confirm.

**Comment by arindamchoudhury** [comment]
@satterly  I can confirm that it is because of grpcio.

**Comment by satterly** [comment]
Ok. Then I think this is an issue for the grpcio and/or flask developers. I'll close this issue.
