### ISSUE TITLE
Housekeeping fails when using postgresql

### ISSUE THREAD

**Issue by Anderen2** [alerta/alerta#528]
It seems like the latest update implementing shelving of alarms broke the housekeeping for PostgreSQL ( https://github.com/alerta/alerta/commit/0d36ac624a481e01c5d0598603582824219c578b ).

Sample housekeeping call:
```
[root@snip ~]# curl -H "Authorization: Key snip" localhost/api/management/housekeeping 
{
  "code": 503, 
  "errors": null, 
  "message": "HOUSEKEEPING FAILED: Type names and field names can only contain alphanumeric characters and underscores: '?column?'", 
  "status": "error"
}
```

UWSGI log:
```
2018-04-28 00:06:43,862 - alerta[18702]: ERROR - HOUSEKEEPING FAILED: Type names and field names can only contain alphanumeric characters and underscores: '?column?' [in /usr/lib/python2.7/site-packages/alerta_server-5.2.0_-py2.7.egg/alerta/exceptions.py:67]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/alerta_server-5.2.0_-py2.7.egg/alerta/auth/utils.py", line 95, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/alerta_server-5.2.0_-py2.7.egg/alerta/management/views.py", line 148, in housekeeping
    raise ApiError('HOUSEKEEPING FAILED: %s' % e, 503)
ApiError: HOUSEKEEPING FAILED: Type names and field names can only contain alphanumeric characters and underscores: '?column?'
```

PostgreSQL version and query output
```
[root@snip ~]# psql -V    
psql (PostgreSQL) 10.1

alerta=> SELECT id, event, 'expired', last_receive_id                                                                                                                                                            
              FROM alerts
             WHERE status NOT IN ('expired','shelved') AND timeout!=0
               AND (last_receive_time + INTERVAL '1 second' * timeout) < (NOW() at time zone 'utc')
;
                  id                  |               event                | ?column? |           last_receive_id            
--------------------------------------+------------------------------------+----------+--------------------------------------
 4a3cf7b3-a551-4f67-9614-1e8ca38b50d6 | snip                               | expired  | 5cdfc5b2-5201-460b-ae93-54efe78341b4
 f39d03df-6739-41bc-a9fb-39596b077dda | snip                               | expired  | f669b691-2fe1-424f-ad18-f54ad228f286
 10d0298e-cf07-4365-b3b8-60b645dac686 | snip                               | expired  | 844ec0ef-763d-4c91-a3fa-3641c5de32c5
```

The reason for why this breaks seems to be the implementation of the static values 'expired' and 'open' into the SQL queries, eg at this line: https://github.com/alerta/alerta/commit/0d36ac624a481e01c5d0598603582824219c578b#diff-4ce195a446bf6bd6317dcf15395c7033R835 

This causes PostgreSQL to set the column name for the static values to "?column?", which in combination with the usage of psycopg2.extras.NamedTupleCursor breaks as named tuples does not support the use of "?" in the field names (ref. https://docs.python.org/2/library/collections.html#collections.namedtuple ). 

There are several solutions I see that may fix this issue: 
- Rework postgres/base.py to use the default Tuple-based cursor or DictCursor instead of NamedTupleCursor.
- Rework postgres/base.py, mongodb/base.py and models/alert.py to support returning two tuples, one containing the unshelved alerts and one containing the expired alerts, instead of modifying the DB result and merging the two as done currently.
- Use the default Tuple-based cursor only for the housekeeping function in postgres/base.py.

In my opinion the second choice is the most cleanest, however I'd like to hear your opinion before I started work on a pull-request. 

I've already tested out the last choice as it was the fastest way to confirm the issue, added diff below. 

```
--- base    2018-04-28 00:53:22.128758615 +0200
+++ fixed 2018-04-28 01:13:31.249752570 +0200
@@ -5,6 +5,7 @@
 import psycopg2
 from flask import current_app, g
 from psycopg2.extensions import register_adapter, adapt, AsIs
+from psycopg2.extensions import cursor as TupleCursor
 from psycopg2.extras import NamedTupleCursor, register_composite, Json
 
 from alerta.database.base import Database
@@ -859,6 +860,9 @@
     def housekeeping(self, expired_threshold, info_threshold):
         # delete 'closed' or 'expired' alerts older than "expired_threshold" hours
         # and 'informational' alerts older than "info_threshold" hours
+
+        cursor = g.db.cursor(cursor_factory=TupleCursor)
+
         delete = """
             DELETE FROM alerts
              WHERE (status IN ('closed', 'expired')
@@ -875,7 +879,9 @@
              WHERE status NOT IN ('expired','shelved') AND timeout!=0
                AND (last_receive_time + INTERVAL '1 second' * timeout) < (NOW() at time zone 'utc')
         """
-        expired = self._fetchall(update, {})
+        cursor.execute(update, {})
+        expired = cursor.fetchall()
+        # expired = self._fetchall(update, {})
 
         # get list of alerts to be unshelved
         update = """
@@ -884,7 +890,8 @@
              WHERE status='shelved'
                AND (last_receive_time + INTERVAL '1 second' * timeout) < (NOW() at time zone 'utc')
         """
-        unshelved = self._fetchall(update, {})
+        cursor.execute(update, {})
+        unshelved = cursor.fetchall()
 
         return expired + unshelved
```

**Comment by satterly** [comment]
Thanks. Yes, I agree the second option is probably best for now. A PR would be very welcome. :smile:

**Comment by Anderen2** [comment]
Pull request created :) 

As a sidenote I had issues getting shelving to work, however I might have misunderstood their purpose. 

Is it so that shelved alarms should be unshelved (and put back into open) after a housekeeping run has figured out that the shelving interval has passed? 
If so, are alarms which are active and keep getting duplicates (thus setting last_receive_time) supposed to be indefinitely shelved or may it be something I broke with my pull-request? 

As an example, the following alarm was shelved for 1 hour for an hour ago. 
```
alerta=> SELECT id, event, timeout, last_receive_time, last_receive_id
              FROM alerts
             WHERE status='shelved';
                  id                  |       event       | timeout |    last_receive_time    |           last_receive_id            
--------------------------------------+-------------------+---------+-------------------------+--------------------------------------
 651dc237-ec50-40ee-ab99-d9dbfa02a193 | disk.used_percent |    3600 | 2018-04-29 00:44:40.495 | f15bcec3-cea5-4aa5-b7f0-c7035834e443
(1 row)
```

However, as shown in the query done by the housekeeping job it does not get unshelved as the last_receive_time (which keeps getting updated for each duplicate) plus timeout never gets to be less than the current time, thus being shelved indefinitely. 
```
alerta=> SELECT id, event, last_receive_id                                                                                                                                                                       
              FROM alerts
             WHERE status='shelved'
               AND (last_receive_time + INTERVAL '1 second' * timeout) < (NOW() at time zone 'utc');
 id | event | last_receive_id 
----+-------+-----------------
(0 rows)

```

**Comment by satterly** [comment]
That's a bug.
