### ISSUE TITLE
Error with fresh setup of alerta with PostgreSQL

### ISSUE THREAD

**Issue by viq** [alerta/alerta#541]
Fresh installation of alerta on debian 8, running `alerta query` results in:
```
[Fri May 11 17:10:04.053293 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174] mod_wsgi (pid=22047): Target WSGI script '/var/www/api.wsgi' cannot be loaded as Python module.                                            
[Fri May 11 17:10:04.053332 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174] mod_wsgi (pid=22047): Exception occurred processing WSGI script '/var/www/api.wsgi'.                                                       
[Fri May 11 17:10:04.053355 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174] Traceback (most recent call last):
[Fri May 11 17:10:04.053391 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]   File "/var/www/api.wsgi", line 6, in <module>                                                                                            
[Fri May 11 17:10:04.053396 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]     from alerta import app as application
[Fri May 11 17:10:04.053414 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]   File "/opt/alerta/.venv/lib/python3.4/site-packages/alerta/__init__.py", line 2, in <module>                                             
[Fri May 11 17:10:04.053419 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]     app = create_app()
[Fri May 11 17:10:04.053436 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]   File "/opt/alerta/.venv/lib/python3.4/site-packages/alerta/app.py", line 43, in create_app                                               
[Fri May 11 17:10:04.053441 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]     db.init_db(app)
[Fri May 11 17:10:04.053458 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]   File "/opt/alerta/.venv/lib/python3.4/site-packages/alerta/database/base.py", line 46, in init_db                                        
[Fri May 11 17:10:04.053462 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]     self.create_engine(app, uri=app.config['DATABASE_URL'], dbname=app.config['DATABASE_NAME'])                                            
[Fri May 11 17:10:04.053480 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]   File "/opt/alerta/.venv/lib/python3.4/site-packages/alerta/database/backends/postgres/base.py", line 57, in create_engine                
[Fri May 11 17:10:04.053484 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]     conn.cursor().execute(f.read())
[Fri May 11 17:10:04.053501 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]   File "/opt/alerta/.venv/lib/python3.4/site-packages/psycopg2/extras.py", line 316, in execute                                            
[Fri May 11 17:10:04.053505 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]     return super(NamedTupleCursor, self).execute(query, vars)                                                                              
[Fri May 11 17:10:04.053520 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174] psycopg2.ProgrammingError: syntax error at or near "NOT"                                                                                   
[Fri May 11 17:10:04.053524 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174] LINE 136: CREATE UNIQUE INDEX IF NOT EXISTS env_res_evt_cust_key ON al...
[Fri May 11 17:10:04.053527 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]                                  ^
[Fri May 11 17:10:04.053530 2018] [wsgi:error] [pid 22047:tid 140369154098944] [remote ::1:15174]                     
```

**Comment by satterly** [comment]
what version of postgres is this?

**Comment by satterly** [comment]
I've just done a quick google and I think Debian 8 is at postgres 9.4 however Alerta requires postgres 9.5 or later.
