### ISSUE TITLE
alert-query message too long for logging debug output

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#55]
```
(alerta)nsatterl@GNM40834:~$ alert-query --days 1 --debug
Alerta Report Tool
  api server: monitoring.dc2.gnm:8080
    timezone: Europe/London
    interval: 2014/01/07 11:09:13 - 2014/01/08 11:09:13
     sort by: lastReceiveTime

Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 808, in emit
    self.socket.send(msg)
error: [Errno 90] Message too long
Logged from file api.py, line 124
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 808, in emit
    self.socket.send(msg)
error: [Errno 90] Message too long
Logged from file api.py, line 139
```

**Comment by satnico** [comment]
test

**Comment by satnico** [comment]
test 2

**Comment by satterly** [comment]
test 3
