### ISSUE TITLE
TypeError raised in CloudWatch webhook handler

### ISSUE THREAD

**Issue by evaryont** [alerta/alerta#565]
```
Traceback (most recent call last):
  File "/opt/alerta/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/alerta/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/alerta/venv/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/opt/alerta/venv/lib/python3.5/site-packages/alerta/auth/utils.py", line 95, in wrapped
    return f(*args, **kwargs)
  File "/opt/alerta/venv/lib/python3.5/site-packages/alerta/webhooks/cloudwatch.py", line 81, in cloudwatch
    incomingAlert = parse_notification(request.data)
  File "/opt/alerta/venv/lib/python3.5/site-packages/alerta/webhooks/cloudwatch.py", line 29, in parse_notification
    notification = json.loads(notification)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

* Python 3.5.2
* Alerta API 5.2.2

**Comment by satterly** [comment]
Any chance you could provide the POST data that generated this error? Thanks.

**Comment by evaryont** [comment]
Sure, here it is, with some obfuscation:

```
2018-07-06 10:49:27,408 - alerta[12227]: INFO - Webhook Request:
POST http://alerta.strongmind.com/webhooks/cloudwatch?api-key=123456_abcdef_789ghijk
User-Agent: Amazon Simple Notification Service Agent
Content-Type: text/plain; charset=UTF-8
Host: alerta.strongmind.com
X-Amz-Sns-Message-Id: 5dfd8765-aaaa-bbbb-cccc-123456789abc
X-Forwarded-Proto: http
Content-Length: 1522
X-Amz-Sns-Topic-Arn: arn:aws:sns:us-west-2:1234567890:alerta
X-Forwarded-For: 127.0.0.1
Connection: close
X-Amz-Sns-Message-Type: SubscriptionConfirmation
X-Real-Ip: 127.0.0.1
Accept-Encoding: gzip,deflate
[1B blob data]
{
  "Type" : "SubscriptionConfirmation",
  "MessageId" : "5dfd8765-aaaa-bbbb-cccc-123456789abc",
  "Token" : "2336412f37fb687f5d51e6e241da92fd72d769cb72def7671e41f100397c9582336412f37fb687f5d51e6e241da92fd72d769cb72def7671e41f100397c958671e41f100397c9582336412f37fb687f5d51e6e241da92fd72d769cb72def7671e41f100397c958a1",
  "TopicArn" : "arn:aws:sns:us-west-2:1234567890:alerta",
  "Message" : "You have chosen to subscribe to the topic arn:aws:sns:us-west-2:1234567890:alerta.\nTo confirm the subscriptionDataBuilder, visit the SubscribeURL included in this message.",
  "SubscribeURL" : "https://sns.us-west-2.amazonaws.com/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:us-west-2:1234567890:alerta&Token=2336412f37fb687f5d51e6e241da92fd72d769cb72def7671e41f100397c9582336412f37fb687f5d51e6e241da92fd72d769cb72def7671e41f100397c958671e41f100397c9582336412f37fb687f5d51e6e241da92fd72d769cb72def7671e41f100397c958a1",
  "Timestamp" : "2018-07-06T17:48:23.276Z",
  "SignatureVersion" : "1",
  "Signature" : "ccbL0J7/9notGbO3B6M39htqtwLnglqqf0X17vX7NOxhP7TWCzZ4qw9tcVrO1G5WQCmZDGj69GsGIEqTsgcVlDZc038tcdmnYEUHwY27/ar0haSXM80M0YgtUm1e8QO/bNlB4rLTU5cQklqvBJUh/n3ncjjnLNsug90duJMFWTYEIVpLlw37pTIizO/1TjdIU2x0PCbJzSsttkQEwQVkOTS5+XKPHAZVxO8+6Jpvr8RC0ml5GXGXCMIMV90UF4m356+3v27NpdiThxzylWqXKXA2GuEuNE+zcAzbM3ewgx+V2a+VciBlUgsP+VpmsKFG8+v/esEPQih/sN0tv7XNsQ==",
  "SigningCertURL" : "https://sns.us-west-2.amazonaws.com/SimpleNotificationService-eaea6120e66ea12e88dcd8bcbddca752.pem"
} [in /opt/alerta/venv/lib/python3.5/site-packages/alerta/webhooks/__init__.py:18]
2018-07-06 10:49:27,416 - alerta[12227]: ERROR - the JSON object must be str, not 'bytes' [in /opt/alerta/venv/lib/python3.5/site-packages/alerta/exceptions.py:77]
Traceback (most recent call last):
  File "/opt/alerta/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/alerta/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/alerta/venv/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/opt/alerta/venv/lib/python3.5/site-packages/alerta/auth/utils.py", line 95, in wrapped
    return f(*args, **kwargs)
  File "/opt/alerta/venv/lib/python3.5/site-packages/alerta/webhooks/cloudwatch.py", line 81, in cloudwatch
    incomingAlert = parse_notification(request.data)
  File "/opt/alerta/venv/lib/python3.5/site-packages/alerta/webhooks/cloudwatch.py", line 29, in parse_notification
    notification = json.loads(notification)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
b'' - - [06/Jul/2018:10:49:27 -0700] "POST /webhooks/cloudwatch?api-key=no5HYOn_7jHLAgQKJWQElWe_K7t4wekDJn9xWb7b HTTP/1.0" 500 1234 "-" "Amazon Simple Notification Service Agent"
```

**Comment by satterly** [comment]
Seems this is a problem only with python 3.5 (ie. python 2.7 and python 3.6 work fine)...

<img width="942" alt="screen shot 2018-07-08 at 23 56 28" src="https://user-images.githubusercontent.com/615057/42424318-ba5c1836-830a-11e8-85ad-0cc3c59aa773.png">

**Comment by satterly** [comment]
Fixed by using the `request.json` helper method instead of `json.loads()`.

**Comment by evaryont** [comment]
Interesting that it didn't affect 3.6. Thanks for the quick fix!

**Comment by evaryont** [comment]
Unfortunately, this is not enough. Another stack trace:

```
gunicorn[23042]: {
gunicorn[23042]:   "Type" : "SubscriptionConfirmation",
gunicorn[23042]:   "MessageId" : "64409099-aaaa-bbbb-cccc-123456789abc",
gunicorn[23042]:   "Token" : "2336412f37fb687f5d51e6e241da92fd72d769cb72def7671e41f100397c9582336412f37fb687f5d51e6e241da92fd72d769cb72def7671e41f100397c958671e41f100397c9582336412f37fb687f5d51e6e241da92fd72d769cb72def7671e41f100397c958a1
gunicorn[23042]:   "TopicArn" : "arn:aws:sns:us-west-2:123456789012:alerta",
gunicorn[23042]:   "Message" : "You have chosen to subscribe to the topic arn:aws:sns:us-west-2:123456789012:alerta.\nTo confirm the subscriptionDataBuild
gunicorn[23042]:   "SubscribeURL" : "https://sns.us-west-2.amazonaws.com/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:us-west-2:123456789012:alerta&To
gunicorn[23042]:   "Timestamp" : "2018-07-11T21:40:54.307Z",
gunicorn[23042]:   "SignatureVersion" : "1",
gunicorn[23042]:   "Signature" : "SftG0Sk6Rncf5uo9jHfeZqFhHeq03mYFzy1K3uSJSd/2uvJwi8p/KYLX/I3VFiYR+h8FXcn8AL4tjngOH8ggjV5B+k44msrqiCzeZ6s3DOS00XaWUnta2JXK
gunicorn[23042]:   "SigningCertURL" : "https://sns.us-west-2.amazonaws.com/SimpleNotificationService-eaea6120e66ea12e88dcd8bcbddca752.pem"
gunicorn[23042]: } [in /opt/alerta/venv/lib/python3.5/site-packages/alerta/webhooks/__init__.py:18]
gunicorn[23042]: 2018-07-11 14:42:04,491 - alerta[23049]: ERROR - 'NoneType' object is not subscriptable [in /opt/alerta/venv/lib/python3.5/site-packages/
gunicorn[23042]: Traceback (most recent call last):
gunicorn[23042]:   File "/opt/alerta/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
gunicorn[23042]:     rv = self.dispatch_request()
gunicorn[23042]:   File "/opt/alerta/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
gunicorn[23042]:     return self.view_functions[rule.endpoint](**req.view_args)
gunicorn[23042]:   File "/opt/alerta/venv/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
gunicorn[23042]:     resp = make_response(f(*args, **kwargs))
gunicorn[23042]:   File "/opt/alerta/venv/lib/python3.5/site-packages/alerta/auth/utils.py", line 95, in wrapped
gunicorn[23042]:     return f(*args, **kwargs)
gunicorn[23042]:   File "/opt/alerta/venv/lib/python3.5/site-packages/alerta/webhooks/cloudwatch.py", line 79, in cloudwatch
gunicorn[23042]:     incomingAlert = parse_notification(request.json)
gunicorn[23042]:   File "/opt/alerta/venv/lib/python3.5/site-packages/alerta/webhooks/cloudwatch.py", line 29, in parse_notification
gunicorn[23042]:     if notification['Type'] == 'SubscriptionConfirmation':
gunicorn[23042]: TypeError: 'NoneType' object is not subscriptable
```

**Comment by satterly** [comment]
Ok. Thanks. Any chance you could test this on python 3.6?
