### ISSUE TITLE
Problems with Alerta Web UI

### ISSUE THREAD

**Issue by PMDubuc** [alerta/alerta#568]
Just installed alerta-5.2.0 and can't run alertad.  Python version is 2.7.12.

$ alertad run --port 8080
2018-07-10 10:50:48,626 - raven.base.Client[15608]: INFO - Raven is not configured (logging is disabled). Please see the documentation for more information. [in /usr/local/lib/python2.7/dist-packages/raven/base.py:218]
2018-07-10 10:50:48,742 - alerta.plugins[15608]: INFO - Server plugin 'reject' enabled. [in /usr/local/lib/python2.7/dist-packages/alerta/utils/plugin.py:31]
2018-07-10 10:50:48,744 - alerta.plugins[15608]: INFO - Server plugin 'blackout' enabled. [in /usr/local/lib/python2.7/dist-packages/alerta/utils/plugin.py:31]
2018-07-10 10:50:48,745 - alerta.plugins[15608]: INFO - All server plugins enabled: reject, blackout [in /usr/local/lib/python2.7/dist-packages/alerta/utils/plugin.py:34]
2018-07-10 10:50:48,774 - alerta.plugins[15608]: INFO - No plugin routing rules found. All plugins will be evaluated. [in /usr/local/lib/python2.7/dist-packages/alerta/utils/plugin.py:38]
Traceback (most recent call last):
  File "/usr/local/bin/alertad", line 7, in <module>
    from alerta.commands import cli
  File "/usr/local/lib/python2.7/dist-packages/alerta/commands.py", line 4, in <module>
    from flask.cli import FlaskGroup, with_appcontext
ImportError: No module named cli

**Comment by PMDubuc** [comment]
Tried python 3.5.2:
$ python3 /usr/local/bin/alertad run
Traceback (most recent call last):
  File "/usr/local/bin/alertad", line 7, in <module>
    from alerta.commands import cli
ImportError: No module named 'alerta'

Are the install instruction out of date for this version?  I'm installing on ubuntu:
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by satterly** [comment]
What install instructions are you referring to?

**Comment by PMDubuc** [comment]
here:
https://github.com/alerta/alerta
and here:
http://alerta.readthedocs.io/en/latest/quick-start.html

**Comment by PMDubuc** [comment]
Doing the install with pip3 seems to solve the problem.

**Comment by satterly** [comment]
Ok Thanks. I'll review those instructions and see if I can reproduce your error.

**Comment by PMDubuc** [comment]
So I have alertad running.  When I install and run the web console (https://github.com/alerta/alerta)
there are map files missing and I get 404 errors.  Are the map file missing from the package?

[10/Jul/2018 15:12:19] "GET / HTTP/1.1" 200 -
[10/Jul/2018 15:12:19] "GET /vendor/css/bootstrap.min.css HTTP/1.1" 200 -
[10/Jul/2018 15:12:19] "GET /css/app.css HTTP/1.1" 200 -
[10/Jul/2018 15:12:19] "GET /vendor/js/jquery.min.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /vendor/js/bootstrap.min.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /vendor/js/angular.min.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /vendor/js/angular-route.min.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /vendor/js/angular-sanitize.min.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /vendor/js/angular-resource.min.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /config.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /js/app.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /js/services.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /js/controllers.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /js/filters.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /js/directives.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /vendor/js/satellizer.min.js HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] "GET /img/loading.gif HTTP/1.1" 200 -
[10/Jul/2018 15:12:20] code 404, message File not found
[10/Jul/2018 15:12:20] "GET /vendor/js/angular.min.js.map HTTP/1.1" 404 -
[10/Jul/2018 15:12:20] code 404, message File not found
[10/Jul/2018 15:12:20] "GET /vendor/js/angular-route.min.js.map HTTP/1.1" 404 -
[10/Jul/2018 15:12:20] code 404, message File not found
[10/Jul/2018 15:12:20] "GET /vendor/js/angular-resource.min.js.map HTTP/1.1" 404 -
[10/Jul/2018 15:12:21] code 404, message File not found
[10/Jul/2018 15:12:21] "GET /vendor/js/angular-sanitize.min.js.map HTTP/1.1" 404 -
[10/Jul/2018 15:12:22] code 404, message File not found
[10/Jul/2018 15:12:22] "GET /vendor/css/bootstrap.min.css.map HTTP/1.1" 404 -

**Comment by PMDubuc** [comment]
Nevermind the above.  I guess those map files are only needed for debugging.  I'm trying to figure out why the console isn't displaying the alerts I'm sending.

**Comment by satterly** [comment]
It could be a CORS issue ... http://alerta.readthedocs.io/en/latest/faq.html#why-can-t-i-see-any-alerts-in-the-web-browser

**Comment by satterly** [comment]
This is a bug that was fixed [here](https://github.com/alerta/angular-alerta-webui/pull/139) Are you running the most up-to-date version of the web UI?

**Comment by PMDubuc** [comment]
Yes.  I have that version.  I downloaded it yesterday:
$ ls -l
total 2388
drwxrwxr-x 6 ubuntu ubuntu    4096 Jul 10 14:39 alerta-angular-alerta-webui-**c1439f7**
-rw-rw-r-- 1 ubuntu ubuntu 2437681 Jul 10 13:18 alerta-web.tgz

**Comment by satterly** [comment]
I've been able to reproduce the behaviour you're seeing where the web UI shows "Refreshing..." constantly if the "endpoint" configuration setting is wrong. Are you sure the Alerta API is running on localhost and on port 5000?
Your output from the first comment you submitted seems to suggest you are running Alerta API on port 8080. From above ...
```
$ alertad run --port 8080
2018-07-10 10:50:48,626 - raven.base.Client[15608]: INFO - Raven is not configured (logging is disabled). Please see the documentation for more information. [in /usr/local/lib/python2.7/dist-packages/raven/base.py:218]
```

**Comment by PMDubuc** [comment]
I'm now running the web UI with the this config.js:
```
'use strict';

angular.module('config', [])
  .constant('config', {
    'endpoint'        : "/api",
    'provider'        : "gitlab", // google, github, gitlab, keycloak, pingfederate, saml2 or basic
    'client_id'       : "f7b8dbd6753074f21fcb8dcdbe567d270b80af01587ea7750576694f2115589f",
  })
  .constant('colors', {});
```
I've configure alertad to use our gitlab for authenication according to the instructions here:  http://alerta.readthedocs.io/en/latest/authentication.html

The UI is trying to refresh the alerts and is giving these messages:
```
[12/Jul/2018 16:22:35] code 404, message File not found
[12/Jul/2018 16:22:35] "GET /api/services?status=open&status=unknown HTTP/1.1" 404 -
[12/Jul/2018 16:22:35] code 404, message File not found
[12/Jul/2018 16:22:35] "GET /api/alerts/count?status=open&status=unknown HTTP/1.1" 404 -
```

When I try to log in, I get:
`[12/Jul/2018 16:29:44] "GET /undefined/oauth/authorize?response_type=code&client_id=f7b8dbd6753074f21fcb8dcdbe567d270b80af01587ea7750576694f2115589f&redirect_uri=http://10.243.42.139:8000 HTTP/1.1" 404 -`

What am i doing wrong?

**Comment by satterly** [comment]
You're missing the Gitlab URL ... 
```
 'gitlab_url'      : "https://gitlab.com",  // replace with your gitlab server
```
See https://github.com/alerta/angular-alerta-webui/blob/master/app/config.js#L9

**Comment by satterly** [comment]
And what's the full URL path to your Alerta API ? It is really being hosted at "http://localhost/api" ?

**Comment by PMDubuc** [comment]
Thanks for your help, Nick.

I did switch to using port 8080.
I fixed the refresh error messages by changing the endpoint in the web UI config to "http://<IP Addr>:8080" instead of "/api"

Now the refresh requests are going to alertad, but I'm still getting the same oauth error when I try to log in.

**Comment by satterly** [comment]
You need to set the "gitlab_url" config variable in the `config.js` to the URL of your gitlab server.

**Comment by PMDubuc** [comment]
Thanks!  I added the gitlab_url and now  I get the authorization request from gitlab.  Clicking the Authorize button doesn't seem to do anything.  I get a popup with some JSON

`{"data":null,"status":-1,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"withCredentials":false,"url":"http://XX.XXX.XX.XXX:8080/auth/gitlab","data":{"code":"6f2d160b0b64d221a5ff2c98b44a09dc0f41777a9f1125454093b1f7ed47317c","clientId":"f7b8dbd6753074f21fcb8dcdbe567d270b80af01587ea7750576694f2115589f","redirectUri":"http://XX.XXX.XX.XXX:8000"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":""}`

I click OK on that and just get the "Please login to continue" page back witout geting logged in.  My Alerta application in gitlab doesn't seem to be getting authorized.

> And what's the full URL path to your Alerta API ? It is really being hosted at "http://localhost/api" ?
I'm using the IP address instead of a host name since I I'm just trying to see if I can integrate Alerta with our Prometheus monitor I don't have the DNS set up yet.  Suo I'm using http://XX.XXX.XX.XXX:8080 for the endpoint URL in the config.js.  I see refresh requests come in on the alertad log with a successful (200) status, but the UI doesn't update and show the alerts.  I know there are alerts in the database because I can seem them using the history command on the CLI.

**Comment by satterly** [comment]
I'm confused, because further up you said the API endpoint was "/api" ...
```
    'endpoint'        : "/api",
```

Can you paste below the (redacted) current `config.js` and API `alertad.conf` files that you have in place right now?

**Comment by PMDubuc** [comment]
Sure, thanks.  Sorry for the confustion.  I've been trying diffrent things to get this to work.

config.js:

```
'use strict';

angular.module('config', [])
  .constant('config', {
    'endpoint'        : "http://XX.XXX.XX.XXX:8080",
    'provider'        : "gitlab", // google, github, gitlab, keycloak, pingfederate, saml2 or basic
    'gitlab_url'      : "https://gitlab.xxxxxx.org",
    'client_id'       : "f7b8dbd6753074f21fcb8dcdbe567d270b80af01587ea7750576694f2115589f"
  })
  .constant('colors', {});
```
alertad.conf:

```
DEBUG = True
AUTH_REQUIRED = True
ADMIN_USERS = ['pdubuc@xxxxxxx.org']
SECRET_KEY = 'CnJ9Ese!=4(26LuoTu1Y(V9QdUV5zm8*'
GITLAB_URL = 'https://gitlab.xxxxxxx.org'
OAUTH2_CLIENT_ID = 'f7b8dbd6753074f21fcb8dcdbe567d270b80af01587ea7750576694f2115589f'
OAUTH2_CLIENT_SECRET = 'f72c607ff2abd26322e7830706680ba71b7a41517cfb2a68becc35935afaab9f'
ALLOWED_GITLAB_GROUPS = ['ops']
```

**Comment by PMDubuc** [comment]
Progress:  I'm trying somthing different, deploying the alera server according to these instructions:  http://docs.alerta.io/en/latest/gettingstarted/tutorial-1-deploy-alerta.html
I can see the alerts I send in the UI now but when I click on them, the only thing I can do is "Shelve" them.  The other Ack, Close and Delete buttons don't work and I can Unshelve them once they've been shelved.  Is this because I need to set up authentication for those function to work?  I don't have that working yet in this configuration.

**Comment by satterly** [comment]
Some require auth some admin privileges.

**Comment by PMDubuc** [comment]
I think I've got everything working now, deploying as a uWsgi server.  Thanks for your help, Nick!
