### ISSUE TITLE
exception errors after upgrading from version 6.0.1

### ISSUE THREAD

**Issue by charlesalloum** [alerta/alerta#713]
hello, 
i was running on version 6.0.1 without any errors.
after upgrading ( same errors on all newer versions 6.1.0, 6.2.0 , 6.2.1 ) when i run the api with "gunicorn --bind 0.0.0.0:8000 alerta:app"  i get these errors: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/alerta/webhooks/prometheus.py", line 110, in prometheus
    alert = process_alert(incomingAlert)
  File "/usr/local/lib/python3.5/dist-packages/alerta/utils/api.py", line 64, in process_alert
    raise ApiError(str(e))
alerta.exceptions.ApiError: 'normal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/alerta/auth/decorators.py", line 103, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/alerta/webhooks/prometheus.py", line 114, in prometheus
    raise ApiError(str(e), 500)
alerta.exceptions.ApiError: 'normal'

**Comment by satterly** [comment]
I've worked out that this only happened if you use custom severity levels that don't include the severity "normal". The bug was introduced [here](https://github.com/alerta/alerta/pull/687) and fixed [here](https://github.com/alerta/alerta/pull/718). If you upgrade to Release 6.3.0 it will work. Thanks for reporting this.
