### ISSUE TITLE
api 500

### ISSUE THREAD

**Issue by skob** [alerta/alerta#835]
I can see regular error 500 on latest alerta api with stack:

```
alerta/views/alerts.py", line 64, in receive
    raise ApiError(str(e), 500)
alerta.exceptions.ApiError: duplicate key value violates unique constraint "env_res_evt_cust_key"```

(pg / mongo backend tried , clear db tried)

how can I debug this error to help fix this bug?

**Comment by skob** [comment]
```
ERROR:flask.app:duplicate key value violates unique constraint "env_res_evt_cust_key"
DETAIL:  Key (environment, resource, event, COALESCE(customer, ''::text))=(, metrica-03, nginx_4X, ) already exists.
Traceback (most recent call last):
  File "/srv/projects/venv3/lib/python3.5/site-packages/alerta/utils/api.py", line 63, in process_alert
    alert = alert.create()
  File "/srv/projects/venv3/lib/python3.5/site-packages/alerta/models/alert.py", line 362, in create
    return Alert.from_db(db.create_alert(self))
  File "/srv/projects/venv3/lib/python3.5/site-packages/alerta/database/backends/postgres/base.py", line 253, in create_alert
    return self._insert(insert, vars(alert))
  File "/srv/projects/venv3/lib/python3.5/site-packages/alerta/database/backends/postgres/base.py", line 1107, in _insert
    cursor.execute(query, vars)
  File "/srv/projects/venv3/lib/python3.5/site-packages/psycopg2/extras.py", line 313, in execute
    return super(NamedTupleCursor, self).execute(query, vars)
psycopg2.IntegrityError: duplicate key value violates unique constraint "env_res_evt_cust_key"
DETAIL:  Key (environment, resource, event, COALESCE(customer, ''::text))=(, metrica-03, nginx_4X, ) already exists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/projects/venv3/lib/python3.5/site-packages/alerta/views/alerts.py", line 53, in receive
    alert = process_alert(alert)
  File "/srv/projects/venv3/lib/python3.5/site-packages/alerta/utils/api.py", line 65, in process_alert
    raise ApiError(str(e))
alerta.exceptions.ApiError: duplicate key value violates unique constraint "env_res_evt_cust_key"
DETAIL:  Key (environment, resource, event, COALESCE(customer, ''::text))=(, metrica-03, nginx_4X, ) already exists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/projects/venv3/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/projects/venv3/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/projects/venv3/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/srv/projects/venv3/lib/python3.5/site-packages/alerta/auth/decorators.py", line 49, in wrapped
    return f(*args, **kwargs)
  File "/srv/projects/venv3/lib/python3.5/site-packages/alerta/models/metrics.py", line 259, in wrapped
    response = f(*args, **kwargs)
  File "/srv/projects/venv3/lib/python3.5/site-packages/alerta/utils/response.py", line 19, in decorated
    return func(*args, **kwargs)
  File "/srv/projects/venv3/lib/python3.5/site-packages/alerta/views/alerts.py", line 64, in receive
    raise ApiError(str(e), 500)
alerta.exceptions.ApiError: duplicate key value violates unique constraint "env_res_evt_cust_key"
DETAIL:  Key (environment, resource, event, COALESCE(customer, ''::text))=(, metrica-03, nginx_4X, ) already exists.
```

**Comment by satterly** [comment]
Have you set `customer` to the empty string anywhere when sending alerts?
Or are you using an API key that is associated with a customer that is just
an empty string?

**Comment by skob** [comment]
I suppose I send empty string as customer from my Riemann installation

I’ll check this

**Comment by skob** [comment]
thank you!
I'll check my settings/logs in this direction.

**Comment by satterly** [comment]
What version of Alerta are you running? A check against empty customer strings has been in place since version 6.0.0. See https://github.com/alerta/alerta/pull/619

**Comment by skob** [comment]
I suppose this is trick , yes
I'll update alerta api today + will remove "customer_view=true" from app config
