### ISSUE TITLE
ERROR:flask.app:Error while running pre-receive plugin 'alerta.plugins.blackout': $nin needs an array

### ISSUE THREAD

**Issue by sauber** [alerta/alerta#848]
Running alerta with a custom webhook and filing a http POST request, server reponds with

```
{
  "code": 500,
  "errors": null,
  "message": "Error while running pre-receive plugin 'alerta.plugins.blackout': $nin needs an array",
  "status": "error"
}
```

Server stack trace:

```
(alerta) sd-mac:alerta sauber$ FLASK_APP=alerta FLASK_ENV=development flask run
 * Serving Flask app "alerta" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
 * Restarting with stat
INFO:raven.base.Client:Raven is not configured (logging is disabled). Please see the documentation for more information.
 * Debugger is active!
 * Debugger PIN: 148-078-702
INFO:alerta.plugins:

    Default reject policy will block alerts that do not have the following
    required attributes:
    1) environment - must match an allowed environment. By default it should
       be either "Production" or "Development". Config setting is `ALLOWED_ENVIRONMENTS`.
    2) service - must supply a value for service. Any value is acceptable.


INFO:alerta.plugins:Server plugin 'reject' loaded.
INFO:alerta.plugins:

    Default suppression blackout handler will drop alerts that match a blackout
    period and will return a 202 Accept HTTP status code.

    If "NOTIFICATION_BLACKOUT" is set to ``True`` then the alert is processed
    but alert status is set to "blackout" and the alert will not be passed to
    any plugins for further notification.


INFO:alerta.plugins:Server plugin 'blackout' loaded.
INFO:alerta.plugins:All server plugins enabled: reject, blackout
INFO:alerta.plugins:No plugin routing rules found. All plugins will be evaluated.
INFO:alerta.webhooks:

    Rancher Alertmanager webhook receiver
    See https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver


INFO:flask.app:Server webhook 'rancher' loaded.
INFO:flask.app:Server webhook 'azuremonitor' loaded.
INFO:raven.base.Client:Raven is not configured (logging is disabled). Please see the documentation for more information.
INFO:alerta.plugins:

    Default reject policy will block alerts that do not have the following
    required attributes:
    1) environment - must match an allowed environment. By default it should
       be either "Production" or "Development". Config setting is `ALLOWED_ENVIRONMENTS`.
    2) service - must supply a value for service. Any value is acceptable.


INFO:alerta.plugins:Server plugin 'reject' loaded.
INFO:alerta.plugins:

    Default suppression blackout handler will drop alerts that match a blackout
    period and will return a 202 Accept HTTP status code.

    If "NOTIFICATION_BLACKOUT" is set to ``True`` then the alert is processed
    but alert status is set to "blackout" and the alert will not be passed to
    any plugins for further notification.


INFO:alerta.plugins:Server plugin 'blackout' loaded.
INFO:alerta.plugins:All server plugins enabled: reject, blackout
INFO:alerta.plugins:No plugin routing rules found. All plugins will be evaluated.
INFO:alerta.webhooks:

    Rancher Alertmanager webhook receiver
    See https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver


INFO:flask.app:Server webhook 'rancher' loaded.
INFO:flask.app:Server webhook 'azuremonitor' loaded.
INFO:flask.app:Webhook Request:
POST http://127.0.0.1:8080/webhooks/rancher

Host: 127.0.0.1:8080
User-Agent: curl/7.54.0
Accept: */*
Content-Type: application/json
Content-Length: 1427
Expect: 100-continue

{  "receiver": "c-2xt5z-ca-vnprd",  "status": "firing",  "alerts": [    {      "status": "firing",      "labels": {        "alert_id": "c-2xt5z-ca-vnprd",        "alert_name": "Test",        "alert_type": "nodeMemory",        "cluster_name": "demo",        "mem_threshold": "1",        "node_name": "coreos02",        "severity": "critical",        "total_mem": "6004336Ki",        "used_mem": "1350Mi"      },      "annotations": {},      "startsAt": "2019-01-31T20:53:07.131500641Z",      "endsAt": "0001-01-01T00:00:00Z",      "generatorURL": ""    },    {      "status": "firing",      "labels": {        "alert_id": "c-2xt5z-ca-vnpre",        "alert_name": "Test",        "alert_type": "nodeCPU",        "cluster_name": "demo",        "cpu": "1",        "node_name": "coreos02",        "severity": "critical",        "total_mem": "6004336Ki",        "used_mem": "1350Mi"      },      "annotations": {},      "startsAt": "2019-01-31T20:53:07.131500641Z",      "endsAt": "0001-01-01T00:00:00Z",      "generatorURL": ""    }  ],  "groupLabels": {},  "commonLabels": {    "alert_id": "c-2xt5z-ca-vnprd",    "alert_name": "Test",    "alert_type": "nodeMemory",    "cluster_name": "demo",    "mem_threshold": "1",    "node_name": "coreos02",    "severity": "critical",    "total_mem": "6004336Ki",    "used_mem": "1350Mi"  },  "commonAnnotations": {},  "externalURL": "http://alertmanager-d6c75555d-d94xn:9093",  "version": "4"}
ERROR:flask.app:Error while running pre-receive plugin 'alerta.plugins.blackout': $nin needs an array
Traceback (most recent call last):
  File "/Users/sauber/projects/alerta/alerta/alerta/utils/api.py", line 46, in process_alert
    alert = plugin.pre_receive(alert)
  File "/Users/sauber/projects/alerta/alerta/alerta/plugins/blackout.py", line 24, in pre_receive
    if alert.is_blackout():
  File "/Users/sauber/projects/alerta/alerta/alerta/models/alert.py", line 374, in is_blackout
    return db.is_blackout_period(self)
  File "/Users/sauber/projects/alerta/alerta/alerta/database/backends/mongodb/base.py", line 1059, in is_blackout_period
    if self.get_db().blackouts.find_one(query):
  File "/Users/sauber/projects/alerta/lib/python3.7/site-packages/pymongo/collection.py", line 1262, in find_one
    for result in cursor.limit(-1):
  File "/Users/sauber/projects/alerta/lib/python3.7/site-packages/pymongo/cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "/Users/sauber/projects/alerta/lib/python3.7/site-packages/pymongo/cursor.py", line 1104, in _refresh
    self.__send_message(q)
  File "/Users/sauber/projects/alerta/lib/python3.7/site-packages/pymongo/cursor.py", line 982, in __send_message
    helpers._check_command_response(first)
  File "/Users/sauber/projects/alerta/lib/python3.7/site-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: $nin needs an array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sauber/projects/alerta/alerta/alerta/webhooks/custom.py", line 41, in custom
    alert = process_alert(alert)
  File "/Users/sauber/projects/alerta/alerta/alerta/utils/api.py", line 51, in process_alert
    raise RuntimeError("Error while running pre-receive plugin '{}': {}".format(plugin.name, str(e)))
RuntimeError: Error while running pre-receive plugin 'alerta.plugins.blackout': $nin needs an array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sauber/projects/alerta/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sauber/projects/alerta/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sauber/projects/alerta/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/sauber/projects/alerta/alerta/alerta/auth/decorators.py", line 108, in wrapped
    return f(*args, **kwargs)
  File "/Users/sauber/projects/alerta/alerta/alerta/webhooks/custom.py", line 45, in custom
    raise ApiError(str(e), 500)
alerta.exceptions.ApiError: Error while running pre-receive plugin 'alerta.plugins.blackout': $nin needs an array
127.0.0.1 - - [20/Feb/2019 13:12:16] "POST /webhooks/rancher HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [20/Feb/2019 13:12:16] "POST /webhooks/rancher HTTP/1.1" 500 - 
```

**Comment by sauber** [comment]
The problems seems to be related to the data type of service attribute in Alert()

    return Alert(
        ...
        service = labels.pop('alert_type'),
        ...
    )

**Comment by satterly** [comment]
where are those lines of code from?

**Comment by sauber** [comment]
The code is from a new rancher plugin that I'm developing. I cannot find plugin guide, so I'm guessing what data the plugin needs to produce.

**Comment by satterly** [comment]
Apologies for there not being a guide or tutorial for this. In the meantime you can look at more than a dozen examples either in the [core server repo](https://github.com/alerta/alerta/tree/master/alerta/webhooks) or the [contrib repo](https://github.com/alerta/alerta-contrib/tree/master/webhooks).

The returned alert needs to conform to the standard Alert format which is described in detail [here](https://docs.alerta.io/en/latest/api/alert.html#attributes).

To resolve this particular error, you must return a list or services. See the prometheus webhook for example ...

https://github.com/alerta/alerta/blob/8d0b2ffc0b6bc986241e72759f46eb947489dbb0/alerta/webhooks/prometheus.py#L61
 Let me know if you need more info and/or contact me directly on [Gitter](https://gitter.im/alerta/chat).

**Comment by sauber** [comment]
OK, that's fair.
