### ISSUE TITLE
Alerta CLI ignores --endpoint-url command line argument

### ISSUE THREAD

**Issue by vykulakov** [alerta/alerta#856]
**Describe the bug**
Alerta CLI ignores the `--endpoint-url` command line argument. So when I run `alerta` like this:
```
$ /usr/local/bin/alerta --endpoint-url http://localhost:5000 version
```
I will get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/alerta", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/alertaclient/cli.py", line 54, in cli
    config.get_remote_config()
  File "/usr/local/lib/python3.5/dist-packages/alertaclient/config.py", line 56, in get_remote_config
    r = requests.get(config_url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /config (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f20de1b8d30>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
As we can see, Alerta CLI tries to connect to port `8080` instead of `5000` that I have specified in the command line.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `alertad` on the 5000 port
2. Try to connect to it with `alerta` with the `--endpoint-url` command line argument
3. See error

**Expected behavior**
I expect to see a correct answer from Alerta Server - the version in my case.

**Environment:**
 - OS: Debian 9.7
 - Version:
    - alerta 6.7.3
    - alerta client 6.5.0
    - requests 2.12.4
    - click 7.0

**Additional context**
When I specify the endpoint url in a config file, all will work fine:
```
$ cat /opt/alerta/alerta.conf
[DEFAULT]
endpoint = http://localhost:5000
key = {secret key}
$ /usr/local/bin/alerta --config-file /opt/alerta/alerta.conf version
alerta 6.7.3
alerta client 6.5.0
requests 2.12.4
click 7.0
```

**Comment by satterly** [comment]
Thanks for raising this issue. A fix is in progress and will be included in the next release. 👍
