### ISSUE TITLE
The /oembed.json endpoint returns 500 response code

### ISSUE THREAD

**Issue by vykulakov** [alerta/alerta#860]
**Describe the bug**
The `/oembed.json` endpoint returns 500 response code with the following body:
```
{
"code": 500,
"errors": [
"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.5/dist-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.5/dist-packages/flask/app.py\", line 1791, in dispatch_request\n    self.raise_routing_exception(req)\n  File \"/usr/local/lib/python3.5/dist-packages/flask/app.py\", line 1774, in raise_routing_exception\n    raise request.routing_exception\n  File \"/usr/local/lib/python3.5/dist-packages/flask/ctx.py\", line 336, in match_request\n    self.url_adapter.match(return_rule=True)\n  File \"/usr/local/lib/python3.5/dist-packages/werkzeug/routing.py\", line 1556, in match\n    raise RequestRedirect(redirect_url)\nwerkzeug.routing.RequestRedirect: 301 Moved Permanently: None\n"
],
"message": "301 Moved Permanently: None",
"status": "error"
}
```
In the Alerta log at the same time:
```
Feb 28 14:15:36 localhost alertad[30345]: ERROR 301 Moved Permanently: None
Feb 28 14:15:36 localhost alertad[30345]: Traceback (most recent call last):
Feb 28 14:15:36 localhost alertad[30345]:   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
Feb 28 14:15:36 localhost alertad[30345]:     rv = self.dispatch_request()
Feb 28 14:15:36 localhost alertad[30345]:   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1791, in dispatch_request
Feb 28 14:15:36 localhost alertad[30345]:     self.raise_routing_exception(req)
Feb 28 14:15:36 localhost alertad[30345]:   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1774, in raise_routing_exception
Feb 28 14:15:36 localhost alertad[30345]:     raise request.routing_exception
Feb 28 14:15:36 localhost alertad[30345]:   File "/usr/local/lib/python3.5/dist-packages/flask/ctx.py", line 336, in match_request
Feb 28 14:15:36 localhost alertad[30345]:     self.url_adapter.match(return_rule=True)
Feb 28 14:15:36 localhost alertad[30345]:   File "/usr/local/lib/python3.5/dist-packages/werkzeug/routing.py", line 1556, in match
Feb 28 14:15:36 localhost alertad[30345]:     raise RequestRedirect(redirect_url)
Feb 28 14:15:36 localhost alertad[30345]: werkzeug.routing.RequestRedirect: 301 Moved Permanently: None
```
Results are the same, when I invoke the endpoint with curl, browser or when I use the https://github.com/alerta/alerta/blob/master/examples/oembed.html page on my server.

**To Reproduce**
1. Invoke `/oembed.json`
2. See error

**Expected behavior**
I expect a regular response or more understandable response code (3xx or 4xx).

**Environment:**
 - OS: Debian 9.7
 - Version:
    - alerta 6.7.5
    - alerta client 6.5.0
    - requests 2.21.0
    - click 7.0

**Additional context**
Alertad config file:
```
$ cat /etc/alertad.conf
DEBUG = False
USE_PROXYFIX = True
ALLOWED_ENVIRONMENTS = ['Production', 'Development', 'Testing']

LOG_HANDLERS = ['console']
LOG_FILE = '/var/log/alertad.log'
LOG_MAX_BYTES = 5*1024*1024  # 5 MB
LOG_BACKUP_COUNT = 2
LOG_FORMAT = 'simple'

DATABASE_URL = 'postgresql://correct_url'
DATABASE_NAME = 'alerta'

CORS_ORIGINS = [
    'correct_origin'
]

ADMIN_USERS = ['admin']

AUTH_REQUIRED = True
AUTH_PROVIDER = 'gitlab'
GITLAB_URL = 'gitlab_url'
OAUTH2_CLIENT_ID = 'client_id'
OAUTH2_CLIENT_SECRET = 'client_secret'
ALLOWED_GITLAB_GROUPS = ['correct_group']

ALERT_TIMEOUT = 300
```

**Comment by satterly** [comment]
Fixed by #853
