### ISSUE TITLE
duplicate key error

### ISSUE THREAD

**Issue by wimfabri** [alerta/alerta#872]
**Describe the bug**
When 2 events exist separately, and then one of them is sent with the other as correlated, you get a duplicate key error:

2019-03-05 02:01:52,081 DEBG 'nginx' stdout output:
ip=\134.54.10.136 [\05/Mar/2019:02:01:52 +0000] "\POST /api/alert HTTP/1.0" \500 \286 "\-" "\python-requests/2.21.0"
2019-03-05 02:01:52,127 DEBG 'uwsgi' stdout output:
INFO:flask.app:State Transition: Rule #CLS-* STATE=closed   ACTION=         SET=open     SEVERITY=ok           -> ok       HISTORY=closed  -> closed   => SEVERITY=ok      , STATUS=closed  
2019-03-05 02:01:52,130 DEBG 'uwsgi' stdout output:
ERROR:flask.app:duplicate key value violates unique constraint "env_res_evt_cust_key"
DETAIL:  Key (environment, resource, event, COALESCE(customer, ''::text))=(Agfa_prod, morsuv943_root, morsuv943_root used space 90%, Agfa) already exists.
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/alerta/utils/api.py", line 61, in process_alert
    alert = alert.update()
  File "/venv/lib/python3.6/site-packages/alerta/models/alert.py", line 333, in update
    return Alert.from_db(db.correlate_alert(self, history))
  File "/venv/lib/python3.6/site-packages/alerta/database/backends/postgres/base.py", line 238, in correlate_alert
    return self._updateone(update, vars(alert), returning=True)
  File "/venv/lib/python3.6/site-packages/alerta/database/backends/postgres/base.py", line 1147, in _updateone
    cursor.execute(query, vars)
  File "/venv/lib/python3.6/site-packages/psycopg2/extras.py", line 313, in execute
    return super(NamedTupleCursor, self).execute(query, vars)
psycopg2.IntegrityError: duplicate key value violates unique constraint "env_res_evt_cust_key"
DETAIL:  Key (environment, resource, event, COALESCE(customer, ''::text))=(Agfa_prod, morsuv943_root, morsuv943_root used space 90%, Agfa) already exists.

version: 6.7.5

**Comment by satterly** [comment]
Can you use `alerta` CLI tool to create the exact sequence of events that causes this error? And then paste the commands below so I can reproduce the error locally. Thanks.

**Comment by wimfabri** [comment]
I can't recreate it. I had a situation where I had 2 alert records  where event of record 2 was in the correlate of record 1. I deleted the records to get rid of the error, should have backed them up first ...

**Comment by satterly** [comment]
No problem. If it happens again get a dump of each alert.
