### ISSUE TITLE
AMQP plugin breaks adding alerts

### ISSUE THREAD

**Issue by ajgon** [alerta/alerta#906]
**Issue Summary**
After installing AMQP plugin, I am unable to add any event to alerta backend.

**Environment**
- OS: Linux
- API version: 6.8.3
- Deployment: Docker

- Database: Postgres

- Env variables
```ini
ADMIN_KEY=...
ADMIN_PASSWORD=...
ADMIN_USERS=alerta@test.host
ALERTA_CONF_FILE=/app/alerta.conf
ALERTA_SVR_CONF_FILE=/app/alertad.conf
ALERTA_WEB_CONF_FILE=/web/config.json
AMQP_TOPIC=alerta.notify
AUTH_REQUIRED=True
BASE_URL=/api
DATABASE_URL=postgres://...
GPG_KEY=[...]
HEARTBEAT_SEVERITY=major
INSTALL_PLUGINS=normalise,enhance,amqp
LANG=C.UTF-8
MAIL_FROM=alerta@test.host
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/venv/bin
PLUGINS=reject,blackout,normalise,enhance,amqp
PYTHON_PIP_VERSION=19.0.3
PYTHONUNBUFFERED=1
PYTHON_VERSION=3.6.8
REDIS_URL=redis://redis:6379/
```

- Server config:
```json
{
    "actions": [],
    "alarm_model": {
        "colors": {
            "highlight": "skyblue ",
            "severity": {
                "cleared": "#00CC00",
                "critical": "red",
                "debug": "#9D006D",
                "indeterminate": "lightblue",
                "informational": "#00CC00",
                "major": "orange",
                "minor": "yellow",
                "normal": "#00CC00",
                "ok": "#00CC00",
                "security": "blue",
                "trace": "#7554BF",
                "unknown": "silver",
                "warning": "dodgerblue"
            },
            "text": "black"
        },
        "name": "Alerta 6.8.3",
        "severity": {
            "cleared": 7,
            "critical": 1,
            "debug": 8,
            "indeterminate": 5,
            "informational": 6,
            "major": 2,
            "minor": 3,
            "normal": 7,
            "ok": 7,
            "security": 0,
            "trace": 9,
            "unknown": 10,
            "warning": 4
        },
        "status": {
            "ack": "C",
            "assign": "B",
            "blackout": "E",
            "closed": "F",
            "expired": "G",
            "open": "A",
            "shelved": "D",
            "unknown": "H"
        }
    },
    "audio": {
        "new": null
    },
    "auth_required": true,
    "azure_tenant": null,
    "client_id": null,
    "colors": {
        "highlight": "skyblue ",
        "severity": {
            "cleared": "#00CC00",
            "critical": "red",
            "debug": "#9D006D",
            "indeterminate": "lightblue",
            "informational": "#00CC00",
            "major": "orange",
            "minor": "yellow",
            "normal": "#00CC00",
            "ok": "#00CC00",
            "security": "blue",
            "trace": "#7554BF",
            "unknown": "silver",
            "warning": "dodgerblue"
        },
        "text": "black"
    },
    "columns": [
        "severity",
        "status",
        "lastReceiveTime",
        "duplicateCount",
        "customer",
        "environment",
        "service",
        "resource",
        "event",
        "value",
        "text"
    ],
    "customer_views": false,
    "dates": {
        "longDate": "d/M/yyyy h:mm:ss.sss a",
        "mediumDate": "EEE d MMM HH:mm",
        "shortTime": "HH:mm"
    },
    "email_verification": true,
    "endpoint": "http://alerta:8080/api",
    "github_url": "https://github.com",
    "gitlab_url": "https://gitlab.com",
    "keycloak_realm": null,
    "keycloak_url": null,
    "oidc_auth_url": null,
    "pingfederate_url": null,
    "provider": "basic",
    "refresh_interval": 5000,
    "severity": {
        "cleared": 7,
        "critical": 1,
        "debug": 8,
        "indeterminate": 5,
        "informational": 6,
        "major": 2,
        "minor": 3,
        "normal": 7,
        "ok": 7,
        "security": 0,
        "trace": 9,
        "unknown": 10,
        "warning": 4
    },
    "signup_enabled": false,
    "site_logo_url": "",
    "sort_by": "lastReceiveTime",
    "tracking_id": null
}
```

- web UI version: 6.8.3
- CLI version: 6.8.3

**To Reproduce**
1. Install AMQP Plugin
2. Send dummy report `alerta send -r tester -e test -E Production -s critical -S Web`

**Expected behavior**
Issue should be reported and queued into AMQP.

**Actual behavior**
CLI returns:

```
ERROR: Error while running post-receive plugin 'alerta_amqp': replace() takes no keyword arguments
```

alerta logs:

```
2019-04-01 13:10:21,443 DEBG 'uwsgi' stdout output:
[pid: 106|app: 0|req: 7/16] 172.28.0.4 () {38 vars in 431 bytes} [Mon Apr  1 13:10:21 2019] GET /api/config => generated 703 bytes in 2 msecs (HTTP/1.0 200) 6 headers in 180 bytes (1 switches on core 0)

2019-04-01 13:10:21,444 DEBG 'nginx' stdout output:
ip=\- [\01/Apr/2019:13:10:21 +0000] "\GET /api/config HTTP/1.0" \200 \703 "\-" "\python-requests/2.12.4"

2019-04-01 13:10:21,461 DEBG 'uwsgi' stdout output:
INFO:alerta.plugins.normalise:Normalising alert...

2019-04-01 13:10:21,463 DEBG 'uwsgi' stdout output:
INFO:alerta.plugins.enhance:Enhancing alert...

2019-04-01 13:10:21,465 DEBG 'uwsgi' stdout output:
INFO:flask.app:State Transition: Rule #ALL-* STATE=open     ACTION=         SET=open     SEVERITY=indeterminate-> critical HISTORY=open    -> open     => SEVERITY=critical, STATUS=open

2019-04-01 13:10:21,469 DEBG 'uwsgi' stdout output:
INFO:alerta.plugins.amqp:Sending message b71341de-3bd3-41bd-ba18-f1949d3ebad6 to AMQP topic "alerta.notify"

2019-04-01 13:10:21,470 DEBG 'uwsgi' stdout output:
ERROR:flask.app:Error while running post-receive plugin 'alerta_amqp': replace() takes no keyword arguments
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/alerta/utils/api.py", line 72, in process_alert
    updated = plugin.post_receive(alert)
  File "/venv/lib/python3.6/site-packages/alerta_amqp.py", line 51, in post_receive
    body = alert.get_body()
  File "/venv/lib/python3.6/site-packages/alerta/models/alert.py", line 150, in get_body
    key: DateTime.iso8601(body[key]) for key in ['createTime', 'lastReceiveTime', 'receiveTime', 'updateTime']
  File "/venv/lib/python3.6/site-packages/alerta/models/alert.py", line 150, in <dictcomp>
    key: DateTime.iso8601(body[key]) for key in ['createTime', 'lastReceiveTime', 'receiveTime', 'updateTime']
  File "/venv/lib/python3.6/site-packages/alerta/utils/format.py", line 42, in iso8601
    return dt.replace(microsecond=0).strftime('%Y-%m-%dT%H:%M:%S') + '.%03dZ' % (dt.microsecond // 1000)
TypeError: replace() takes no keyword arguments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/alerta/views/alerts.py", line 53, in receive
    alert = process_alert(alert)
  File "/venv/lib/python3.6/site-packages/alerta/utils/api.py", line 75, in process_alert
    raise ApiError("Error while running post-receive plugin '{}': {}".format(plugin.name, str(e)))
alerta.exceptions.ApiError: Error while running post-receive plugin 'alerta_amqp': replace() takes no keyword arguments

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/venv/lib/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/venv/lib/python3.6/site-packages/alerta/auth/decorators.py", line 49, in wrapped
    return f(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/alerta/models/metrics.py", line 259, in wrapped
    response = f(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/alerta/utils/response.py", line 19, in decorated
    return func(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/alerta/views/alerts.py", line 64, in receive
    raise ApiError(str(e), 500)
alerta.exceptions.ApiError: Error while running post-receive plugin 'alerta_amqp': replace() takes no keyword arguments

2019-04-01 13:10:21,478 DEBG 'nginx' stdout output:
ip=\- [\01/Apr/2019:13:10:21 +0000] "\POST /api/alert HTTP/1.0" \500 \148 "\-" "\python-requests/2.12.4"

2019-04-01 13:10:21,478 DEBG 'uwsgi' stdout output:
[pid: 106|app: 0|req: 8/17] 172.28.0.4 () {44 vars in 578 bytes} [Mon Apr  1 13:10:21 2019] POST /api/alert => generated 148 bytes in 26 msecs (HTTP/1.0 500) 4 headers in 152 bytes (1 switches on core 0)
```

**Comment by ajgon** [comment]
Seems like, problem lies here:
https://github.com/alerta/alerta/blob/12e05a9dc8a74ebd64e5141f45fbe8d5ea1a8139/alerta/models/alert.py#L150 

`body[key]` contains string instead of datetime for whatever reason. I patched my instance by adding `if type(dt) == str: return dt` check to `utils/format.py`, and it resolved the issue. Probably it's not the desired approach, but works for now :)

**Comment by ashwinbasavaraja** [comment]
I am seeing similar issue via the integration with logstash custom plug-in integration to load the alert data into elastic search via logstash plug-in. 

ERROR:alerta.plugins.logstash:replace() takes no keyword arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/alerta_logstash.py", line 45, in post_receive
    self.sock.send(b"%s\r\n" % json.dumps(alert.get_body(history=False)).encode('utf-8'))
  File "/usr/lib/python3.6/site-packages/alerta/models/alert.py", line 150, in get_body
    key: DateTime.iso8601(body[key]) for key in ['createTime', 'lastReceiveTime', 'receiveTime', 'updateTime']
  File "/usr/lib/python3.6/site-packages/alerta/models/alert.py", line 150, in <dictcomp>
    key: DateTime.iso8601(body[key]) for key in ['createTime', 'lastReceiveTime', 'receiveTime', 'updateTime']
  File "/usr/lib/python3.6/site-packages/alerta/utils/format.py", line 42, in iso8601
    return dt.replace(microsecond=0).strftime('%Y-%m-%dT%H:%M:%S') + '.%03dZ' % (dt.microsecond // 1000)
TypeError: replace() takes no keyword arguments

**Comment by satterly** [comment]
Is this a Python2 / Python3 thing? ie. I'm not sure all the contributed plugins and integrations have been converted to work with Python 3 yet. Any chance you could test this in a python 2 virtual environment?

**Comment by ashwinbasavaraja** [comment]
It is failing for python3 due to some recent changes happened in alert model. As Ajgon reported, 'updateTime' is None incase of new alert. When the date formate is applied it fails as body['updateTime'] == None. 

It needs below changes, Try to create pull request, looks like I lag permission to do the diff. My diff list below & it is similar to Ajgon reported

--- a/alerta/models/alert.py
+++ b/alerta/models/alert.py
@@ -153,8 +153,14 @@ class Alert:

     def get_body(self, history: bool=True) -> Dict[str, Any]:
         body = self.serialize
+
+
+        keys2Replace = ['createTime', 'lastReceiveTime', 'receiveTime']
+        if body['updateTime'] != None:
+            keys2Replace.append('updateTime')
+
         body.update({
-            key: DateTime.iso8601(body[key]) for key in ['createTime', 'lastReceiveTime', 'receiveTime', 'updateTime']
+            key: DateTime.iso8601(body[key]) for key in keys2Replace
         })

**Comment by satterly** [comment]
Thanks. If you fork the repo you can create a pull request in the forked repo and it will default to opening that pull request against this repo. Please try and let me know if that works for you.

**Comment by satterly** [comment]
As explained in #925 it's easier just to skip the null values. Also, there was a problem with Postgres that was fixed at the same time.  You will need to run ...
```
ALTER TABLE alerts DROP COLUMN update_time;
```

**Comment by ashwinbasavaraja** [comment]
Perfect. Thanks for the quick response.
