### ISSUE TITLE
500 Error in services response

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#945]
```
web_1  |
web_1  | 2019-04-22 20:19:16,460 DEBG 'uwsgi' stdout output:
web_1  | ERROR:flask.app:('Development', '2926')
web_1  | Traceback (most recent call last):
web_1  |   File "/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
web_1  |     rv = self.dispatch_request()
web_1  |   File "/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
web_1  |     return self.view_functions[rule.endpoint](**req.view_args)
web_1  |   File "/venv/lib/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
web_1  |     resp = make_response(f(*args, **kwargs))
web_1  |   File "/venv/lib/python3.6/site-packages/alerta/auth/decorators.py", line 74, in wrapped
web_1  |     return f(*args, **kwargs)
web_1  |   File "/venv/lib/python3.6/site-packages/alerta/models/metrics.py", line 259, in wrapped
web_1  |     response = f(*args, **kwargs)
web_1  |   File "/venv/lib/python3.6/site-packages/alerta/utils/response.py", line 19, in decorated
web_1  |     return func(*args, **kwargs)
web_1  |   File "/venv/lib/python3.6/site-packages/alerta/views/alerts.py", line 510, in get_services
web_1  |     services = Alert.get_services(query)
web_1  |   File "/venv/lib/python3.6/site-packages/alerta/models/alert.py", line 528, in get_services
web_1  |     return db.get_services(query)
web_1  |   File "/venv/lib/python3.6/site-packages/alerta/database/backends/postgres/base.py", line 628, in get_services
web_1  |     } for env, svc in severity_count]
web_1  |   File "/venv/lib/python3.6/site-packages/alerta/database/backends/postgres/base.py", line 628, in <listcomp>
web_1  |     } for env, svc in severity_count]
web_1  | KeyError: ('Development', '2926')
web_1  |
web_1  | 2019-04-22 20:19:16,497 DEBG 'nginx' stdout output:
web_1  | ip=\- [\22/Apr/2019:20:19:16 +0000] "\GET /api/services HTTP/1.1" \500 \1566 "\http://localhost:8080/alerts" "\Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
```

**Comment by satterly** [comment]
Can not reproduce so closing until there is more information to work with.
