### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by arindamchoudhury** [alerta/alerta#980]
**Issue Summary**
Getting this error while posting alert.
**Environment**
- OS: Linux
- API version:7.2.7
- Deployment:  Docker
- Database: Postgres

- Server config:
```
  {'actions': [],
 'alarm_model': {'colors': {'highlight': 'skyblue ',
   'severity': {'cleared': '#00CC00',
    'critical': 'red',
    'debug': '#9D006D',
    'indeterminate': 'lightblue',
    'informational': '#00CC00',
    'major': 'orange',
    'minor': 'yellow',
    'normal': '#00CC00',
    'ok': '#00CC00',
    'security': 'blue',
    'trace': '#7554BF',
    'unknown': 'silver',
    'warning': 'dodgerblue'},
   'text': 'black'},
  'defaults': {'normal_severity': 'normal',
   'previous_severity': 'indeterminate',
   'status': 'open'},
  'name': 'Alerta 7.2.7',
  'severity': {'cleared': 5,
   'critical': 1,
   'debug': 7,
   'fatal': 0,
   'indeterminate': 5,
   'informational': 6,
   'major': 2,
   'minor': 4,
   'normal': 5,
   'ok': 5,
   'trace': 8,
   'unknown': 9,
   'warning': 3},
  'status': {'ack': 'C',
   'assign': 'B',
   'blackout': 'E',
   'closed': 'F',
   'expired': 'G',
   'open': 'A',
   'shelved': 'D',
   'unknown': 'H'}},
 'audio': {'new': None},
 'auth_required': True,
 'azure_tenant': None,
 'client_id': 'XXXXXXX.apps.googleusercontent.com',
 'colors': {'highlight': 'skyblue ',
  'severity': {'cleared': '#00CC00',
   'critical': 'red',
   'debug': '#9D006D',
   'indeterminate': 'lightblue',
   'informational': '#00CC00',
   'major': 'orange',
   'minor': 'yellow',
   'normal': '#00CC00',
   'ok': '#00CC00',
   'security': 'blue',
   'trace': '#7554BF',
   'unknown': 'silver',
   'warning': 'dodgerblue'},
  'text': 'black'},
 'columns': ['severity',
  'status',
  'lastReceiveTime',
  'timeoutLeft',
  'duplicateCount',
  'customer',
  'environment',
  'service',
  'resource',
  'event',
  'value'],
 'customer_views': True,
 'dates': {'longDate': 'd/M/yyyy h:mm:ss.sss a',
  'mediumDate': 'EEE d MMM HH:mm',
  'shortTime': 'HH:mm'},
 'debug': False,
 'email_verification': False,
 'endpoint': 'http://alerta.XXXXXXX.com:8082/api',
 'github_url': 'https://github.com',
 'gitlab_url': 'https://gitlab.com',
 'keycloak_realm': None,
 'keycloak_url': None,
 'oidc_auth_url': None,
 'pingfederate_url': None,
 'provider': 'google',
 'refresh_interval': 5000,
 'severity': {'cleared': 5,
  'critical': 1,
  'debug': 7,
  'fatal': 0,
  'indeterminate': 5,
  'informational': 6,
  'major': 2,
  'minor': 4,
  'normal': 5,
  'ok': 5,
  'trace': 8,
  'unknown': 9,
  'warning': 3},
 'signup_enabled': False,
 'site_logo_url': 'https://XXXXXXX/img/grafana_icon.svg',
 'sort_by': 'lastReceiveTime',
 'tracking_id': None}
```
- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

The stacktrace:

```
ERROR:flask.app:'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/alerta_server-7.2.7-py3.7.egg/alerta/auth/decorators.py", line 50, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/alerta_server-7.2.7-py3.7.egg/alerta/models/metrics.py", line 259, in wrapped
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/alerta_server-7.2.7-py3.7.egg/alerta/utils/response.py", line 19, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/alerta_server-7.2.7-py3.7.egg/alerta/views/alerts.py", line 68, in receive
    write_audit_trail.send(current_app._get_current_object(), event='alert-received', message=alert.text, user=g.login,
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by satterly** [comment]
For every alert or a specific alert? If only a specific alert please include the alert. Thanks.

**Comment by arindamchoudhury** [comment]
last happened while posting this alert:

`alerta_api.api.send_alert("XXXXX/host=XXXXX/disk-usage-grow-rate/path=/XXXXX/mysql/backups", "disk-usage-grow-rate", environment="prod", severity="normal", value="1.23", customer="XXXXX", text= "disk-usage-grow-rate: Value 1.23 is acceptable", service=["agent:telegraf"], origin="alert_check", group="mysql", type= "alert:default", attributes= {'field': 'used_percent', 'function': 'mean', 'title': 'Disk usage grow is high', 'group_by': ['path'], 'path': '/XXXXX/mysql/backups', 'kind': 'alert:default', 'nodata': 'critical', 'group_by_time': '15m', 'fill': 'none', 'window': '1h', '_filter': '{"host": "XXXXX", "path": "/XXXXX/mysql/backups"}', 'transformations': ['derivative(30m)'], 'host': 'XXXXX', 'measurement': 'disk', '_internal:link': '<a href="https://XXXXX.com/dashboard/db/XXXXX?refresh=5m&orgId=9" target="_new">XXXXX</a>'}, tags=['replica', 'mysql', 'XXXXX'])`

But upon retry, it succeeded.

**Comment by satterly** [comment]
So you're using the Python SDK? That would have been useful to know earlier. And as you can't reliably reproduce this error it won't be possible for me to investigate this any further at this stage. If it happens again, in a predictable way, please add more information to this issue. Thanks.
