### ISSUE TITLE
No settings for users when using GitHub OAuth and Postgres backend

### ISSUE THREAD

**Issue by michael-doubez** [alerta/alerta#992]
**Issue Summary**
When using a postgresql backend and github authentication, user can login but get an error in settings.

**Environment**
- OS:  Linux
- API version: 7.2.0
- Deployment: self-hosted
- For self-hosted, WSGI environment: nginx/uwsgi

- Database:  Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? GitHub
  Customer views? No

- web UI version: 7.2.0
- CLI version: 6.8.1

**To Reproduce**
1. Login with GitHub
2. Go to User settings
3. See error
4. Cannot use user settings

    Operator does not exist: text = integer LINE 1: SELECT * FROM users WHERE id=2017 ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. (500)

    Error: Could not retrieve user preferences.

**Expected behavior**
Set user settings

**Additional context**

In Postgres I see id with characters (ex: 9611d676-da02-469b-98f0-...).
The PostGres request seems to expect using integral id.

**Comment by satterly** [comment]
Please provide server config and full error logs. Thanks.

**Comment by michael-doubez** [comment]
Relevant config

```
BASE_URL= '/'

PLUGINS = ['reject', 'blackout', 'heartbeat', 'prometheus']
ALLOWED_ENVIRONMENTS = ['Production']


DATABASE_URL="postgresql://*****:*****@<host>:<port>/alerta"
DATABASE_NAME="alerta"

CORS_ORIGINS = [
    'http://alerta'
]
# Authentication
AUTH_REQUIRED = True
SECRET_KEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
CUSTOMER_VIEWS = False
AUTH_PROVIDER = 'github'
OAUTH2_CLIENT_ID = 'YYYYYYYYYYYYYYYYYYYYY'
OAUTH2_CLIENT_SECRET = 'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ'
ALLOWED_GITHUB_ORGS = ['ORG'']

ADMIN_USERS=["mdoubez" ]
ADMIN_KEY="admin"
USER_DEFAULT_SCOPES = ['admin']

# AlertManager
ALERTMANAGER_API_URL = 'http://localhost:9093'
ALERTMANAGER_SILENCE_DAYS = 1
ALERT_TIMEOUT = 60
```

Relevant logs:

```
INFO:werkzeug:184.58.26.38 - - [05/Jun/2019 10:17:42] "OPTIONS /user/me/attributes HTTP/1.1" 200 -
ERROR:flask.app:operator does not exist: text = integer
LINE 1: SELECT * FROM users WHERE id=2017
                                    ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
Traceback (most recent call last):
  File "/home/rtprod/service/fr_alerta_service_009/lib/alerta/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rtprod/service/fr_alerta_service_009/lib/alerta/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rtprod/service/fr_alerta_service_009/lib/alerta/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/rtprod/service/fr_alerta_service_009/lib/alerta/lib/python3.7/site-packages/alerta/auth/decorators.py", line 74, in wrapped
    return f(*args, **kwargs)
  File "/home/rtprod/service/fr_alerta_service_009/lib/alerta/lib/python3.7/site-packages/alerta/utils/response.py", line 19, in decorated
    return func(*args, **kwargs)
  File "/home/rtprod/service/fr_alerta_service_009/lib/alerta/lib/python3.7/site-packages/alerta/views/users.py", line 119, in get_me_attributes
    user = User.find_by_id(g.user_id)
  File "/home/rtprod/service/fr_alerta_service_009/lib/alerta/lib/python3.7/site-packages/alerta/models/user.py", line 141, in find_by_id
    return User.from_db(db.get_user(id))
  File "/home/rtprod/service/fr_alerta_service_009/lib/alerta/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py", line 885, in get_user
    return self._fetchone(select, (id,))
  File "/home/rtprod/service/fr_alerta_service_009/lib/alerta/lib/python3.7/site-packages/alerta/database/backends/postgres/base.py", line 1278, in _fetchone
    cursor.execute(query, vars)
  File "/home/rtprod/service/fr_alerta_service_009/lib/alerta/lib/python3.7/site-packages/psycopg2/extras.py", line 319, in execute
    return super(NamedTupleCursor, self).execute(query, vars)
psycopg2.errors.UndefinedFunction: operator does not exist: text = integer
LINE 1: SELECT * FROM users WHERE id=2017
                                    ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Comment by satterly** [comment]
What version of postgres?

**Comment by michael-doubez** [comment]
Postgres version: 9.6

Thanks for investigating

**Comment by satterly** [comment]
Fixed in version 7.2.10

**Comment by michael-doubez** [comment]
I'll test it tomorrow. Many thanks

**Comment by michael-doubez** [comment]
Unexpectedly, I had to remove users in database from past incarnations of our alerta.
It worked right way. Great job!

You've just made many sysadmin happy (well ... let say a little less grumpy).
Thanks
